// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RefreshBatchesColumns holds the columns for the "refresh_batches" table.
	RefreshBatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RefreshBatchesTable holds the schema information for the "refresh_batches" table.
	RefreshBatchesTable = &schema.Table{
		Name:       "refresh_batches",
		Columns:    RefreshBatchesColumns,
		PrimaryKey: []*schema.Column{RefreshBatchesColumns[0]},
	}
	// RefreshBatchJobsColumns holds the columns for the "refresh_batch_jobs" table.
	RefreshBatchJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "succeeded", "failed"}, Default: "pending"},
		{Name: "attempt", Type: field.TypeInt, Default: 0},
		{Name: "error_reason", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "batch_id", Type: field.TypeUUID},
		{Name: "repo_id", Type: field.TypeUUID},
	}
	// RefreshBatchJobsTable holds the schema information for the "refresh_batch_jobs" table.
	RefreshBatchJobsTable = &schema.Table{
		Name:       "refresh_batch_jobs",
		Columns:    RefreshBatchJobsColumns,
		PrimaryKey: []*schema.Column{RefreshBatchJobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "refresh_batch_jobs_refresh_batches_jobs",
				Columns:    []*schema.Column{RefreshBatchJobsColumns[6]},
				RefColumns: []*schema.Column{RefreshBatchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "refresh_batch_jobs_repositories_refresh_jobs",
				Columns:    []*schema.Column{RefreshBatchJobsColumns[7]},
				RefColumns: []*schema.Column{RepositoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "refreshbatchjob_batch_id_repo_id",
				Unique:  true,
				Columns: []*schema.Column{RefreshBatchJobsColumns[6], RefreshBatchJobsColumns[7]},
			},
			{
				Name:    "refreshbatchjob_batch_id_status",
				Unique:  false,
				Columns: []*schema.Column{RefreshBatchJobsColumns[6], RefreshBatchJobsColumns[1]},
			},
			{
				Name:    "refreshbatchjob_status",
				Unique:  false,
				Columns: []*schema.Column{RefreshBatchJobsColumns[1]},
			},
		},
	}
	// RepositoriesColumns holds the columns for the "repositories" table.
	RepositoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "owner", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "full_name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "stars", Type: field.TypeInt, Default: 0},
		{Name: "language", Type: field.TypeString, Nullable: true},
		{Name: "html_url", Type: field.TypeString},
		{Name: "notes", Type: field.TypeString, Default: ""},
		{Name: "fetched_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RepositoriesTable holds the schema information for the "repositories" table.
	RepositoriesTable = &schema.Table{
		Name:       "repositories",
		Columns:    RepositoriesColumns,
		PrimaryKey: []*schema.Column{RepositoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "repository_language",
				Unique:  false,
				Columns: []*schema.Column{RepositoriesColumns[6]},
			},
			{
				Name:    "repository_stars_id",
				Unique:  false,
				Columns: []*schema.Column{RepositoriesColumns[5], RepositoriesColumns[0]},
			},
			{
				Name:    "repository_updated_at_id",
				Unique:  false,
				Columns: []*schema.Column{RepositoriesColumns[11], RepositoriesColumns[0]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RefreshBatchesTable,
		RefreshBatchJobsTable,
		RepositoriesTable,
	}
)

func init() {
	RefreshBatchJobsTable.ForeignKeys[0].RefTable = RefreshBatchesTable
	RefreshBatchJobsTable.ForeignKeys[1].RefTable = RepositoriesTable
}
