// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/PavaoZornija1/github-tracker/internal/ent/migrate"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatch"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
	"github.com/PavaoZornija1/github-tracker/internal/ent/repository"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// RefreshBatch is the client for interacting with the RefreshBatch builders.
	RefreshBatch *RefreshBatchClient
	// RefreshBatchJob is the client for interacting with the RefreshBatchJob builders.
	RefreshBatchJob *RefreshBatchJobClient
	// Repository is the client for interacting with the Repository builders.
	Repository *RepositoryClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.RefreshBatch = NewRefreshBatchClient(c.config)
	c.RefreshBatchJob = NewRefreshBatchJobClient(c.config)
	c.Repository = NewRepositoryClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		RefreshBatch:    NewRefreshBatchClient(cfg),
		RefreshBatchJob: NewRefreshBatchJobClient(cfg),
		Repository:      NewRepositoryClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		RefreshBatch:    NewRefreshBatchClient(cfg),
		RefreshBatchJob: NewRefreshBatchJobClient(cfg),
		Repository:      NewRepositoryClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		RefreshBatch.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.RefreshBatch.Use(hooks...)
	c.RefreshBatchJob.Use(hooks...)
	c.Repository.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.RefreshBatch.Intercept(interceptors...)
	c.RefreshBatchJob.Intercept(interceptors...)
	c.Repository.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *RefreshBatchMutation:
		return c.RefreshBatch.mutate(ctx, m)
	case *RefreshBatchJobMutation:
		return c.RefreshBatchJob.mutate(ctx, m)
	case *RepositoryMutation:
		return c.Repository.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// RefreshBatchClient is a client for the RefreshBatch schema.
type RefreshBatchClient struct {
	config
}

// NewRefreshBatchClient returns a client for the RefreshBatch from the given config.
func NewRefreshBatchClient(c config) *RefreshBatchClient {
	return &RefreshBatchClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `refreshbatch.Hooks(f(g(h())))`.
func (c *RefreshBatchClient) Use(hooks ...Hook) {
	c.hooks.RefreshBatch = append(c.hooks.RefreshBatch, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `refreshbatch.Intercept(f(g(h())))`.
func (c *RefreshBatchClient) Intercept(interceptors ...Interceptor) {
	c.inters.RefreshBatch = append(c.inters.RefreshBatch, interceptors...)
}

// Create returns a builder for creating a RefreshBatch entity.
func (c *RefreshBatchClient) Create() *RefreshBatchCreate {
	mutation := newRefreshBatchMutation(c.config, OpCreate)
	return &RefreshBatchCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RefreshBatch entities.
func (c *RefreshBatchClient) CreateBulk(builders ...*RefreshBatchCreate) *RefreshBatchCreateBulk {
	return &RefreshBatchCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RefreshBatchClient) MapCreateBulk(slice any, setFunc func(*RefreshBatchCreate, int)) *RefreshBatchCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RefreshBatchCreateBulk{err: fmt.Errorf("calling to RefreshBatchClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RefreshBatchCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RefreshBatchCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RefreshBatch.
func (c *RefreshBatchClient) Update() *RefreshBatchUpdate {
	mutation := newRefreshBatchMutation(c.config, OpUpdate)
	return &RefreshBatchUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RefreshBatchClient) UpdateOne(_m *RefreshBatch) *RefreshBatchUpdateOne {
	mutation := newRefreshBatchMutation(c.config, OpUpdateOne, withRefreshBatch(_m))
	return &RefreshBatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RefreshBatchClient) UpdateOneID(id uuid.UUID) *RefreshBatchUpdateOne {
	mutation := newRefreshBatchMutation(c.config, OpUpdateOne, withRefreshBatchID(id))
	return &RefreshBatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RefreshBatch.
func (c *RefreshBatchClient) Delete() *RefreshBatchDelete {
	mutation := newRefreshBatchMutation(c.config, OpDelete)
	return &RefreshBatchDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RefreshBatchClient) DeleteOne(_m *RefreshBatch) *RefreshBatchDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RefreshBatchClient) DeleteOneID(id uuid.UUID) *RefreshBatchDeleteOne {
	builder := c.Delete().Where(refreshbatch.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RefreshBatchDeleteOne{builder}
}

// Query returns a query builder for RefreshBatch.
func (c *RefreshBatchClient) Query() *RefreshBatchQuery {
	return &RefreshBatchQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRefreshBatch},
		inters: c.Interceptors(),
	}
}

// Get returns a RefreshBatch entity by its id.
func (c *RefreshBatchClient) Get(ctx context.Context, id uuid.UUID) (*RefreshBatch, error) {
	return c.Query().Where(refreshbatch.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RefreshBatchClient) GetX(ctx context.Context, id uuid.UUID) *RefreshBatch {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryJobs queries the jobs edge of a RefreshBatch.
func (c *RefreshBatchClient) QueryJobs(_m *RefreshBatch) *RefreshBatchJobQuery {
	query := (&RefreshBatchJobClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(refreshbatch.Table, refreshbatch.FieldID, id),
			sqlgraph.To(refreshbatchjob.Table, refreshbatchjob.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, refreshbatch.JobsTable, refreshbatch.JobsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RefreshBatchClient) Hooks() []Hook {
	return c.hooks.RefreshBatch
}

// Interceptors returns the client interceptors.
func (c *RefreshBatchClient) Interceptors() []Interceptor {
	return c.inters.RefreshBatch
}

func (c *RefreshBatchClient) mutate(ctx context.Context, m *RefreshBatchMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RefreshBatchCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RefreshBatchUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RefreshBatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RefreshBatchDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RefreshBatch mutation op: %q", m.Op())
	}
}

// RefreshBatchJobClient is a client for the RefreshBatchJob schema.
type RefreshBatchJobClient struct {
	config
}

// NewRefreshBatchJobClient returns a client for the RefreshBatchJob from the given config.
func NewRefreshBatchJobClient(c config) *RefreshBatchJobClient {
	return &RefreshBatchJobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `refreshbatchjob.Hooks(f(g(h())))`.
func (c *RefreshBatchJobClient) Use(hooks ...Hook) {
	c.hooks.RefreshBatchJob = append(c.hooks.RefreshBatchJob, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `refreshbatchjob.Intercept(f(g(h())))`.
func (c *RefreshBatchJobClient) Intercept(interceptors ...Interceptor) {
	c.inters.RefreshBatchJob = append(c.inters.RefreshBatchJob, interceptors...)
}

// Create returns a builder for creating a RefreshBatchJob entity.
func (c *RefreshBatchJobClient) Create() *RefreshBatchJobCreate {
	mutation := newRefreshBatchJobMutation(c.config, OpCreate)
	return &RefreshBatchJobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RefreshBatchJob entities.
func (c *RefreshBatchJobClient) CreateBulk(builders ...*RefreshBatchJobCreate) *RefreshBatchJobCreateBulk {
	return &RefreshBatchJobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RefreshBatchJobClient) MapCreateBulk(slice any, setFunc func(*RefreshBatchJobCreate, int)) *RefreshBatchJobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RefreshBatchJobCreateBulk{err: fmt.Errorf("calling to RefreshBatchJobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RefreshBatchJobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RefreshBatchJobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RefreshBatchJob.
func (c *RefreshBatchJobClient) Update() *RefreshBatchJobUpdate {
	mutation := newRefreshBatchJobMutation(c.config, OpUpdate)
	return &RefreshBatchJobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RefreshBatchJobClient) UpdateOne(_m *RefreshBatchJob) *RefreshBatchJobUpdateOne {
	mutation := newRefreshBatchJobMutation(c.config, OpUpdateOne, withRefreshBatchJob(_m))
	return &RefreshBatchJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RefreshBatchJobClient) UpdateOneID(id uuid.UUID) *RefreshBatchJobUpdateOne {
	mutation := newRefreshBatchJobMutation(c.config, OpUpdateOne, withRefreshBatchJobID(id))
	return &RefreshBatchJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RefreshBatchJob.
func (c *RefreshBatchJobClient) Delete() *RefreshBatchJobDelete {
	mutation := newRefreshBatchJobMutation(c.config, OpDelete)
	return &RefreshBatchJobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RefreshBatchJobClient) DeleteOne(_m *RefreshBatchJob) *RefreshBatchJobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RefreshBatchJobClient) DeleteOneID(id uuid.UUID) *RefreshBatchJobDeleteOne {
	builder := c.Delete().Where(refreshbatchjob.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RefreshBatchJobDeleteOne{builder}
}

// Query returns a query builder for RefreshBatchJob.
func (c *RefreshBatchJobClient) Query() *RefreshBatchJobQuery {
	return &RefreshBatchJobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRefreshBatchJob},
		inters: c.Interceptors(),
	}
}

// Get returns a RefreshBatchJob entity by its id.
func (c *RefreshBatchJobClient) Get(ctx context.Context, id uuid.UUID) (*RefreshBatchJob, error) {
	return c.Query().Where(refreshbatchjob.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RefreshBatchJobClient) GetX(ctx context.Context, id uuid.UUID) *RefreshBatchJob {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBatch queries the batch edge of a RefreshBatchJob.
func (c *RefreshBatchJobClient) QueryBatch(_m *RefreshBatchJob) *RefreshBatchQuery {
	query := (&RefreshBatchClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(refreshbatchjob.Table, refreshbatchjob.FieldID, id),
			sqlgraph.To(refreshbatch.Table, refreshbatch.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, refreshbatchjob.BatchTable, refreshbatchjob.BatchColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRepository queries the repository edge of a RefreshBatchJob.
func (c *RefreshBatchJobClient) QueryRepository(_m *RefreshBatchJob) *RepositoryQuery {
	query := (&RepositoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(refreshbatchjob.Table, refreshbatchjob.FieldID, id),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, refreshbatchjob.RepositoryTable, refreshbatchjob.RepositoryColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RefreshBatchJobClient) Hooks() []Hook {
	return c.hooks.RefreshBatchJob
}

// Interceptors returns the client interceptors.
func (c *RefreshBatchJobClient) Interceptors() []Interceptor {
	return c.inters.RefreshBatchJob
}

func (c *RefreshBatchJobClient) mutate(ctx context.Context, m *RefreshBatchJobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RefreshBatchJobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RefreshBatchJobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RefreshBatchJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RefreshBatchJobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RefreshBatchJob mutation op: %q", m.Op())
	}
}

// RepositoryClient is a client for the Repository schema.
type RepositoryClient struct {
	config
}

// NewRepositoryClient returns a client for the Repository from the given config.
func NewRepositoryClient(c config) *RepositoryClient {
	return &RepositoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `repository.Hooks(f(g(h())))`.
func (c *RepositoryClient) Use(hooks ...Hook) {
	c.hooks.Repository = append(c.hooks.Repository, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `repository.Intercept(f(g(h())))`.
func (c *RepositoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.Repository = append(c.inters.Repository, interceptors...)
}

// Create returns a builder for creating a Repository entity.
func (c *RepositoryClient) Create() *RepositoryCreate {
	mutation := newRepositoryMutation(c.config, OpCreate)
	return &RepositoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Repository entities.
func (c *RepositoryClient) CreateBulk(builders ...*RepositoryCreate) *RepositoryCreateBulk {
	return &RepositoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RepositoryClient) MapCreateBulk(slice any, setFunc func(*RepositoryCreate, int)) *RepositoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RepositoryCreateBulk{err: fmt.Errorf("calling to RepositoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RepositoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RepositoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Repository.
func (c *RepositoryClient) Update() *RepositoryUpdate {
	mutation := newRepositoryMutation(c.config, OpUpdate)
	return &RepositoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RepositoryClient) UpdateOne(_m *Repository) *RepositoryUpdateOne {
	mutation := newRepositoryMutation(c.config, OpUpdateOne, withRepository(_m))
	return &RepositoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RepositoryClient) UpdateOneID(id uuid.UUID) *RepositoryUpdateOne {
	mutation := newRepositoryMutation(c.config, OpUpdateOne, withRepositoryID(id))
	return &RepositoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Repository.
func (c *RepositoryClient) Delete() *RepositoryDelete {
	mutation := newRepositoryMutation(c.config, OpDelete)
	return &RepositoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RepositoryClient) DeleteOne(_m *Repository) *RepositoryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RepositoryClient) DeleteOneID(id uuid.UUID) *RepositoryDeleteOne {
	builder := c.Delete().Where(repository.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RepositoryDeleteOne{builder}
}

// Query returns a query builder for Repository.
func (c *RepositoryClient) Query() *RepositoryQuery {
	return &RepositoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRepository},
		inters: c.Interceptors(),
	}
}

// Get returns a Repository entity by its id.
func (c *RepositoryClient) Get(ctx context.Context, id uuid.UUID) (*Repository, error) {
	return c.Query().Where(repository.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RepositoryClient) GetX(ctx context.Context, id uuid.UUID) *Repository {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRefreshJobs queries the refresh_jobs edge of a Repository.
func (c *RepositoryClient) QueryRefreshJobs(_m *Repository) *RefreshBatchJobQuery {
	query := (&RefreshBatchJobClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repository.Table, repository.FieldID, id),
			sqlgraph.To(refreshbatchjob.Table, refreshbatchjob.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, repository.RefreshJobsTable, repository.RefreshJobsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RepositoryClient) Hooks() []Hook {
	return c.hooks.Repository
}

// Interceptors returns the client interceptors.
func (c *RepositoryClient) Interceptors() []Interceptor {
	return c.inters.Repository
}

func (c *RepositoryClient) mutate(ctx context.Context, m *RepositoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RepositoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RepositoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RepositoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RepositoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Repository mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		RefreshBatch, RefreshBatchJob, Repository []ent.Hook
	}
	inters struct {
		RefreshBatch, RefreshBatchJob, Repository []ent.Interceptor
	}
)
