// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PavaoZornija1/github-tracker/ent/schema"
	"github.com/PavaoZornija1/github-tracker/internal/ent/predicate"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatch"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
	"github.com/PavaoZornija1/github-tracker/internal/ent/repository"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeRefreshBatch    = "RefreshBatch"
	TypeRefreshBatchJob = "RefreshBatchJob"
	TypeRepository      = "Repository"
)

// RefreshBatchMutation represents an operation that mutates the RefreshBatch nodes in the graph.
type RefreshBatchMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	created_at    *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	jobs          map[uuid.UUID]struct{}
	removedjobs   map[uuid.UUID]struct{}
	clearedjobs   bool
	done          bool
	oldValue      func(context.Context) (*RefreshBatch, error)
	predicates    []predicate.RefreshBatch
}

var _ ent.Mutation = (*RefreshBatchMutation)(nil)

// refreshbatchOption allows management of the mutation configuration using functional options.
type refreshbatchOption func(*RefreshBatchMutation)

// newRefreshBatchMutation creates new mutation for the RefreshBatch entity.
func newRefreshBatchMutation(c config, op Op, opts ...refreshbatchOption) *RefreshBatchMutation {
	m := &RefreshBatchMutation{
		config:        c,
		op:            op,
		typ:           TypeRefreshBatch,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRefreshBatchID sets the ID field of the mutation.
func withRefreshBatchID(id uuid.UUID) refreshbatchOption {
	return func(m *RefreshBatchMutation) {
		var (
			err   error
			once  sync.Once
			value *RefreshBatch
		)
		m.oldValue = func(ctx context.Context) (*RefreshBatch, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RefreshBatch.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRefreshBatch sets the old RefreshBatch of the mutation.
func withRefreshBatch(node *RefreshBatch) refreshbatchOption {
	return func(m *RefreshBatchMutation) {
		m.oldValue = func(context.Context) (*RefreshBatch, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RefreshBatchMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RefreshBatchMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of RefreshBatch entities.
func (m *RefreshBatchMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RefreshBatchMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RefreshBatchMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RefreshBatch.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *RefreshBatchMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RefreshBatchMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RefreshBatch entity.
// If the RefreshBatch object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RefreshBatchMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RefreshBatchMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *RefreshBatchMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *RefreshBatchMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the RefreshBatch entity.
// If the RefreshBatch object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RefreshBatchMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *RefreshBatchMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddJobIDs adds the "jobs" edge to the RefreshBatchJob entity by ids.
func (m *RefreshBatchMutation) AddJobIDs(ids ...uuid.UUID) {
	if m.jobs == nil {
		m.jobs = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.jobs[ids[i]] = struct{}{}
	}
}

// ClearJobs clears the "jobs" edge to the RefreshBatchJob entity.
func (m *RefreshBatchMutation) ClearJobs() {
	m.clearedjobs = true
}

// JobsCleared reports if the "jobs" edge to the RefreshBatchJob entity was cleared.
func (m *RefreshBatchMutation) JobsCleared() bool {
	return m.clearedjobs
}

// RemoveJobIDs removes the "jobs" edge to the RefreshBatchJob entity by IDs.
func (m *RefreshBatchMutation) RemoveJobIDs(ids ...uuid.UUID) {
	if m.removedjobs == nil {
		m.removedjobs = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.jobs, ids[i])
		m.removedjobs[ids[i]] = struct{}{}
	}
}

// RemovedJobs returns the removed IDs of the "jobs" edge to the RefreshBatchJob entity.
func (m *RefreshBatchMutation) RemovedJobsIDs() (ids []uuid.UUID) {
	for id := range m.removedjobs {
		ids = append(ids, id)
	}
	return
}

// JobsIDs returns the "jobs" edge IDs in the mutation.
func (m *RefreshBatchMutation) JobsIDs() (ids []uuid.UUID) {
	for id := range m.jobs {
		ids = append(ids, id)
	}
	return
}

// ResetJobs resets all changes to the "jobs" edge.
func (m *RefreshBatchMutation) ResetJobs() {
	m.jobs = nil
	m.clearedjobs = false
	m.removedjobs = nil
}

// Where appends a list predicates to the RefreshBatchMutation builder.
func (m *RefreshBatchMutation) Where(ps ...predicate.RefreshBatch) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RefreshBatchMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RefreshBatchMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RefreshBatch, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RefreshBatchMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RefreshBatchMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RefreshBatch).
func (m *RefreshBatchMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RefreshBatchMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.created_at != nil {
		fields = append(fields, refreshbatch.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, refreshbatch.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RefreshBatchMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case refreshbatch.FieldCreatedAt:
		return m.CreatedAt()
	case refreshbatch.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RefreshBatchMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case refreshbatch.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case refreshbatch.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown RefreshBatch field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RefreshBatchMutation) SetField(name string, value ent.Value) error {
	switch name {
	case refreshbatch.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case refreshbatch.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown RefreshBatch field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RefreshBatchMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RefreshBatchMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RefreshBatchMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RefreshBatch numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RefreshBatchMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RefreshBatchMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RefreshBatchMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RefreshBatch nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RefreshBatchMutation) ResetField(name string) error {
	switch name {
	case refreshbatch.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case refreshbatch.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown RefreshBatch field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RefreshBatchMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.jobs != nil {
		edges = append(edges, refreshbatch.EdgeJobs)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RefreshBatchMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case refreshbatch.EdgeJobs:
		ids := make([]ent.Value, 0, len(m.jobs))
		for id := range m.jobs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RefreshBatchMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedjobs != nil {
		edges = append(edges, refreshbatch.EdgeJobs)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RefreshBatchMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case refreshbatch.EdgeJobs:
		ids := make([]ent.Value, 0, len(m.removedjobs))
		for id := range m.removedjobs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RefreshBatchMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedjobs {
		edges = append(edges, refreshbatch.EdgeJobs)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RefreshBatchMutation) EdgeCleared(name string) bool {
	switch name {
	case refreshbatch.EdgeJobs:
		return m.clearedjobs
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RefreshBatchMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown RefreshBatch unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RefreshBatchMutation) ResetEdge(name string) error {
	switch name {
	case refreshbatch.EdgeJobs:
		m.ResetJobs()
		return nil
	}
	return fmt.Errorf("unknown RefreshBatch edge %s", name)
}

// RefreshBatchJobMutation represents an operation that mutates the RefreshBatchJob nodes in the graph.
type RefreshBatchJobMutation struct {
	config
	op                Op
	typ               string
	id                *uuid.UUID
	status            *schema.RefreshJobStatus
	attempt           *int
	addattempt        *int
	error_reason      *string
	created_at        *time.Time
	updated_at        *time.Time
	clearedFields     map[string]struct{}
	batch             *uuid.UUID
	clearedbatch      bool
	repository        *uuid.UUID
	clearedrepository bool
	done              bool
	oldValue          func(context.Context) (*RefreshBatchJob, error)
	predicates        []predicate.RefreshBatchJob
}

var _ ent.Mutation = (*RefreshBatchJobMutation)(nil)

// refreshbatchjobOption allows management of the mutation configuration using functional options.
type refreshbatchjobOption func(*RefreshBatchJobMutation)

// newRefreshBatchJobMutation creates new mutation for the RefreshBatchJob entity.
func newRefreshBatchJobMutation(c config, op Op, opts ...refreshbatchjobOption) *RefreshBatchJobMutation {
	m := &RefreshBatchJobMutation{
		config:        c,
		op:            op,
		typ:           TypeRefreshBatchJob,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRefreshBatchJobID sets the ID field of the mutation.
func withRefreshBatchJobID(id uuid.UUID) refreshbatchjobOption {
	return func(m *RefreshBatchJobMutation) {
		var (
			err   error
			once  sync.Once
			value *RefreshBatchJob
		)
		m.oldValue = func(ctx context.Context) (*RefreshBatchJob, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RefreshBatchJob.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRefreshBatchJob sets the old RefreshBatchJob of the mutation.
func withRefreshBatchJob(node *RefreshBatchJob) refreshbatchjobOption {
	return func(m *RefreshBatchJobMutation) {
		m.oldValue = func(context.Context) (*RefreshBatchJob, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RefreshBatchJobMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RefreshBatchJobMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of RefreshBatchJob entities.
func (m *RefreshBatchJobMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RefreshBatchJobMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RefreshBatchJobMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RefreshBatchJob.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetBatchID sets the "batch_id" field.
func (m *RefreshBatchJobMutation) SetBatchID(u uuid.UUID) {
	m.batch = &u
}

// BatchID returns the value of the "batch_id" field in the mutation.
func (m *RefreshBatchJobMutation) BatchID() (r uuid.UUID, exists bool) {
	v := m.batch
	if v == nil {
		return
	}
	return *v, true
}

// OldBatchID returns the old "batch_id" field's value of the RefreshBatchJob entity.
// If the RefreshBatchJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RefreshBatchJobMutation) OldBatchID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBatchID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBatchID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBatchID: %w", err)
	}
	return oldValue.BatchID, nil
}

// ResetBatchID resets all changes to the "batch_id" field.
func (m *RefreshBatchJobMutation) ResetBatchID() {
	m.batch = nil
}

// SetRepoID sets the "repo_id" field.
func (m *RefreshBatchJobMutation) SetRepoID(u uuid.UUID) {
	m.repository = &u
}

// RepoID returns the value of the "repo_id" field in the mutation.
func (m *RefreshBatchJobMutation) RepoID() (r uuid.UUID, exists bool) {
	v := m.repository
	if v == nil {
		return
	}
	return *v, true
}

// OldRepoID returns the old "repo_id" field's value of the RefreshBatchJob entity.
// If the RefreshBatchJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RefreshBatchJobMutation) OldRepoID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRepoID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRepoID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRepoID: %w", err)
	}
	return oldValue.RepoID, nil
}

// ResetRepoID resets all changes to the "repo_id" field.
func (m *RefreshBatchJobMutation) ResetRepoID() {
	m.repository = nil
}

// SetStatus sets the "status" field.
func (m *RefreshBatchJobMutation) SetStatus(sjs schema.RefreshJobStatus) {
	m.status = &sjs
}

// Status returns the value of the "status" field in the mutation.
func (m *RefreshBatchJobMutation) Status() (r schema.RefreshJobStatus, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the RefreshBatchJob entity.
// If the RefreshBatchJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RefreshBatchJobMutation) OldStatus(ctx context.Context) (v schema.RefreshJobStatus, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *RefreshBatchJobMutation) ResetStatus() {
	m.status = nil
}

// SetAttempt sets the "attempt" field.
func (m *RefreshBatchJobMutation) SetAttempt(i int) {
	m.attempt = &i
	m.addattempt = nil
}

// Attempt returns the value of the "attempt" field in the mutation.
func (m *RefreshBatchJobMutation) Attempt() (r int, exists bool) {
	v := m.attempt
	if v == nil {
		return
	}
	return *v, true
}

// OldAttempt returns the old "attempt" field's value of the RefreshBatchJob entity.
// If the RefreshBatchJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RefreshBatchJobMutation) OldAttempt(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAttempt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAttempt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAttempt: %w", err)
	}
	return oldValue.Attempt, nil
}

// AddAttempt adds i to the "attempt" field.
func (m *RefreshBatchJobMutation) AddAttempt(i int) {
	if m.addattempt != nil {
		*m.addattempt += i
	} else {
		m.addattempt = &i
	}
}

// AddedAttempt returns the value that was added to the "attempt" field in this mutation.
func (m *RefreshBatchJobMutation) AddedAttempt() (r int, exists bool) {
	v := m.addattempt
	if v == nil {
		return
	}
	return *v, true
}

// ResetAttempt resets all changes to the "attempt" field.
func (m *RefreshBatchJobMutation) ResetAttempt() {
	m.attempt = nil
	m.addattempt = nil
}

// SetErrorReason sets the "error_reason" field.
func (m *RefreshBatchJobMutation) SetErrorReason(s string) {
	m.error_reason = &s
}

// ErrorReason returns the value of the "error_reason" field in the mutation.
func (m *RefreshBatchJobMutation) ErrorReason() (r string, exists bool) {
	v := m.error_reason
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorReason returns the old "error_reason" field's value of the RefreshBatchJob entity.
// If the RefreshBatchJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RefreshBatchJobMutation) OldErrorReason(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorReason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorReason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorReason: %w", err)
	}
	return oldValue.ErrorReason, nil
}

// ClearErrorReason clears the value of the "error_reason" field.
func (m *RefreshBatchJobMutation) ClearErrorReason() {
	m.error_reason = nil
	m.clearedFields[refreshbatchjob.FieldErrorReason] = struct{}{}
}

// ErrorReasonCleared returns if the "error_reason" field was cleared in this mutation.
func (m *RefreshBatchJobMutation) ErrorReasonCleared() bool {
	_, ok := m.clearedFields[refreshbatchjob.FieldErrorReason]
	return ok
}

// ResetErrorReason resets all changes to the "error_reason" field.
func (m *RefreshBatchJobMutation) ResetErrorReason() {
	m.error_reason = nil
	delete(m.clearedFields, refreshbatchjob.FieldErrorReason)
}

// SetCreatedAt sets the "created_at" field.
func (m *RefreshBatchJobMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RefreshBatchJobMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RefreshBatchJob entity.
// If the RefreshBatchJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RefreshBatchJobMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RefreshBatchJobMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *RefreshBatchJobMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *RefreshBatchJobMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the RefreshBatchJob entity.
// If the RefreshBatchJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RefreshBatchJobMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *RefreshBatchJobMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// ClearBatch clears the "batch" edge to the RefreshBatch entity.
func (m *RefreshBatchJobMutation) ClearBatch() {
	m.clearedbatch = true
	m.clearedFields[refreshbatchjob.FieldBatchID] = struct{}{}
}

// BatchCleared reports if the "batch" edge to the RefreshBatch entity was cleared.
func (m *RefreshBatchJobMutation) BatchCleared() bool {
	return m.clearedbatch
}

// BatchIDs returns the "batch" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// BatchID instead. It exists only for internal usage by the builders.
func (m *RefreshBatchJobMutation) BatchIDs() (ids []uuid.UUID) {
	if id := m.batch; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetBatch resets all changes to the "batch" edge.
func (m *RefreshBatchJobMutation) ResetBatch() {
	m.batch = nil
	m.clearedbatch = false
}

// SetRepositoryID sets the "repository" edge to the Repository entity by id.
func (m *RefreshBatchJobMutation) SetRepositoryID(id uuid.UUID) {
	m.repository = &id
}

// ClearRepository clears the "repository" edge to the Repository entity.
func (m *RefreshBatchJobMutation) ClearRepository() {
	m.clearedrepository = true
	m.clearedFields[refreshbatchjob.FieldRepoID] = struct{}{}
}

// RepositoryCleared reports if the "repository" edge to the Repository entity was cleared.
func (m *RefreshBatchJobMutation) RepositoryCleared() bool {
	return m.clearedrepository
}

// RepositoryID returns the "repository" edge ID in the mutation.
func (m *RefreshBatchJobMutation) RepositoryID() (id uuid.UUID, exists bool) {
	if m.repository != nil {
		return *m.repository, true
	}
	return
}

// RepositoryIDs returns the "repository" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// RepositoryID instead. It exists only for internal usage by the builders.
func (m *RefreshBatchJobMutation) RepositoryIDs() (ids []uuid.UUID) {
	if id := m.repository; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetRepository resets all changes to the "repository" edge.
func (m *RefreshBatchJobMutation) ResetRepository() {
	m.repository = nil
	m.clearedrepository = false
}

// Where appends a list predicates to the RefreshBatchJobMutation builder.
func (m *RefreshBatchJobMutation) Where(ps ...predicate.RefreshBatchJob) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RefreshBatchJobMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RefreshBatchJobMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RefreshBatchJob, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RefreshBatchJobMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RefreshBatchJobMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RefreshBatchJob).
func (m *RefreshBatchJobMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RefreshBatchJobMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.batch != nil {
		fields = append(fields, refreshbatchjob.FieldBatchID)
	}
	if m.repository != nil {
		fields = append(fields, refreshbatchjob.FieldRepoID)
	}
	if m.status != nil {
		fields = append(fields, refreshbatchjob.FieldStatus)
	}
	if m.attempt != nil {
		fields = append(fields, refreshbatchjob.FieldAttempt)
	}
	if m.error_reason != nil {
		fields = append(fields, refreshbatchjob.FieldErrorReason)
	}
	if m.created_at != nil {
		fields = append(fields, refreshbatchjob.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, refreshbatchjob.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RefreshBatchJobMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case refreshbatchjob.FieldBatchID:
		return m.BatchID()
	case refreshbatchjob.FieldRepoID:
		return m.RepoID()
	case refreshbatchjob.FieldStatus:
		return m.Status()
	case refreshbatchjob.FieldAttempt:
		return m.Attempt()
	case refreshbatchjob.FieldErrorReason:
		return m.ErrorReason()
	case refreshbatchjob.FieldCreatedAt:
		return m.CreatedAt()
	case refreshbatchjob.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RefreshBatchJobMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case refreshbatchjob.FieldBatchID:
		return m.OldBatchID(ctx)
	case refreshbatchjob.FieldRepoID:
		return m.OldRepoID(ctx)
	case refreshbatchjob.FieldStatus:
		return m.OldStatus(ctx)
	case refreshbatchjob.FieldAttempt:
		return m.OldAttempt(ctx)
	case refreshbatchjob.FieldErrorReason:
		return m.OldErrorReason(ctx)
	case refreshbatchjob.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case refreshbatchjob.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown RefreshBatchJob field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RefreshBatchJobMutation) SetField(name string, value ent.Value) error {
	switch name {
	case refreshbatchjob.FieldBatchID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBatchID(v)
		return nil
	case refreshbatchjob.FieldRepoID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRepoID(v)
		return nil
	case refreshbatchjob.FieldStatus:
		v, ok := value.(schema.RefreshJobStatus)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case refreshbatchjob.FieldAttempt:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAttempt(v)
		return nil
	case refreshbatchjob.FieldErrorReason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorReason(v)
		return nil
	case refreshbatchjob.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case refreshbatchjob.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown RefreshBatchJob field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RefreshBatchJobMutation) AddedFields() []string {
	var fields []string
	if m.addattempt != nil {
		fields = append(fields, refreshbatchjob.FieldAttempt)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RefreshBatchJobMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case refreshbatchjob.FieldAttempt:
		return m.AddedAttempt()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RefreshBatchJobMutation) AddField(name string, value ent.Value) error {
	switch name {
	case refreshbatchjob.FieldAttempt:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAttempt(v)
		return nil
	}
	return fmt.Errorf("unknown RefreshBatchJob numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RefreshBatchJobMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(refreshbatchjob.FieldErrorReason) {
		fields = append(fields, refreshbatchjob.FieldErrorReason)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RefreshBatchJobMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RefreshBatchJobMutation) ClearField(name string) error {
	switch name {
	case refreshbatchjob.FieldErrorReason:
		m.ClearErrorReason()
		return nil
	}
	return fmt.Errorf("unknown RefreshBatchJob nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RefreshBatchJobMutation) ResetField(name string) error {
	switch name {
	case refreshbatchjob.FieldBatchID:
		m.ResetBatchID()
		return nil
	case refreshbatchjob.FieldRepoID:
		m.ResetRepoID()
		return nil
	case refreshbatchjob.FieldStatus:
		m.ResetStatus()
		return nil
	case refreshbatchjob.FieldAttempt:
		m.ResetAttempt()
		return nil
	case refreshbatchjob.FieldErrorReason:
		m.ResetErrorReason()
		return nil
	case refreshbatchjob.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case refreshbatchjob.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown RefreshBatchJob field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RefreshBatchJobMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.batch != nil {
		edges = append(edges, refreshbatchjob.EdgeBatch)
	}
	if m.repository != nil {
		edges = append(edges, refreshbatchjob.EdgeRepository)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RefreshBatchJobMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case refreshbatchjob.EdgeBatch:
		if id := m.batch; id != nil {
			return []ent.Value{*id}
		}
	case refreshbatchjob.EdgeRepository:
		if id := m.repository; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RefreshBatchJobMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RefreshBatchJobMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RefreshBatchJobMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedbatch {
		edges = append(edges, refreshbatchjob.EdgeBatch)
	}
	if m.clearedrepository {
		edges = append(edges, refreshbatchjob.EdgeRepository)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RefreshBatchJobMutation) EdgeCleared(name string) bool {
	switch name {
	case refreshbatchjob.EdgeBatch:
		return m.clearedbatch
	case refreshbatchjob.EdgeRepository:
		return m.clearedrepository
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RefreshBatchJobMutation) ClearEdge(name string) error {
	switch name {
	case refreshbatchjob.EdgeBatch:
		m.ClearBatch()
		return nil
	case refreshbatchjob.EdgeRepository:
		m.ClearRepository()
		return nil
	}
	return fmt.Errorf("unknown RefreshBatchJob unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RefreshBatchJobMutation) ResetEdge(name string) error {
	switch name {
	case refreshbatchjob.EdgeBatch:
		m.ResetBatch()
		return nil
	case refreshbatchjob.EdgeRepository:
		m.ResetRepository()
		return nil
	}
	return fmt.Errorf("unknown RefreshBatchJob edge %s", name)
}

// RepositoryMutation represents an operation that mutates the Repository nodes in the graph.
type RepositoryMutation struct {
	config
	op                  Op
	typ                 string
	id                  *uuid.UUID
	owner               *string
	name                *string
	full_name           *string
	description         *string
	stars               *int
	addstars            *int
	language            *string
	html_url            *string
	notes               *string
	fetched_at          *time.Time
	created_at          *time.Time
	updated_at          *time.Time
	clearedFields       map[string]struct{}
	refresh_jobs        map[uuid.UUID]struct{}
	removedrefresh_jobs map[uuid.UUID]struct{}
	clearedrefresh_jobs bool
	done                bool
	oldValue            func(context.Context) (*Repository, error)
	predicates          []predicate.Repository
}

var _ ent.Mutation = (*RepositoryMutation)(nil)

// repositoryOption allows management of the mutation configuration using functional options.
type repositoryOption func(*RepositoryMutation)

// newRepositoryMutation creates new mutation for the Repository entity.
func newRepositoryMutation(c config, op Op, opts ...repositoryOption) *RepositoryMutation {
	m := &RepositoryMutation{
		config:        c,
		op:            op,
		typ:           TypeRepository,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRepositoryID sets the ID field of the mutation.
func withRepositoryID(id uuid.UUID) repositoryOption {
	return func(m *RepositoryMutation) {
		var (
			err   error
			once  sync.Once
			value *Repository
		)
		m.oldValue = func(ctx context.Context) (*Repository, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Repository.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRepository sets the old Repository of the mutation.
func withRepository(node *Repository) repositoryOption {
	return func(m *RepositoryMutation) {
		m.oldValue = func(context.Context) (*Repository, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RepositoryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RepositoryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Repository entities.
func (m *RepositoryMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RepositoryMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RepositoryMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Repository.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetOwner sets the "owner" field.
func (m *RepositoryMutation) SetOwner(s string) {
	m.owner = &s
}

// Owner returns the value of the "owner" field in the mutation.
func (m *RepositoryMutation) Owner() (r string, exists bool) {
	v := m.owner
	if v == nil {
		return
	}
	return *v, true
}

// OldOwner returns the old "owner" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldOwner(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOwner is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOwner requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOwner: %w", err)
	}
	return oldValue.Owner, nil
}

// ResetOwner resets all changes to the "owner" field.
func (m *RepositoryMutation) ResetOwner() {
	m.owner = nil
}

// SetName sets the "name" field.
func (m *RepositoryMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *RepositoryMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *RepositoryMutation) ResetName() {
	m.name = nil
}

// SetFullName sets the "full_name" field.
func (m *RepositoryMutation) SetFullName(s string) {
	m.full_name = &s
}

// FullName returns the value of the "full_name" field in the mutation.
func (m *RepositoryMutation) FullName() (r string, exists bool) {
	v := m.full_name
	if v == nil {
		return
	}
	return *v, true
}

// OldFullName returns the old "full_name" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldFullName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFullName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFullName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFullName: %w", err)
	}
	return oldValue.FullName, nil
}

// ResetFullName resets all changes to the "full_name" field.
func (m *RepositoryMutation) ResetFullName() {
	m.full_name = nil
}

// SetDescription sets the "description" field.
func (m *RepositoryMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *RepositoryMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldDescription(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *RepositoryMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[repository.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *RepositoryMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[repository.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *RepositoryMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, repository.FieldDescription)
}

// SetStars sets the "stars" field.
func (m *RepositoryMutation) SetStars(i int) {
	m.stars = &i
	m.addstars = nil
}

// Stars returns the value of the "stars" field in the mutation.
func (m *RepositoryMutation) Stars() (r int, exists bool) {
	v := m.stars
	if v == nil {
		return
	}
	return *v, true
}

// OldStars returns the old "stars" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldStars(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStars is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStars requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStars: %w", err)
	}
	return oldValue.Stars, nil
}

// AddStars adds i to the "stars" field.
func (m *RepositoryMutation) AddStars(i int) {
	if m.addstars != nil {
		*m.addstars += i
	} else {
		m.addstars = &i
	}
}

// AddedStars returns the value that was added to the "stars" field in this mutation.
func (m *RepositoryMutation) AddedStars() (r int, exists bool) {
	v := m.addstars
	if v == nil {
		return
	}
	return *v, true
}

// ResetStars resets all changes to the "stars" field.
func (m *RepositoryMutation) ResetStars() {
	m.stars = nil
	m.addstars = nil
}

// SetLanguage sets the "language" field.
func (m *RepositoryMutation) SetLanguage(s string) {
	m.language = &s
}

// Language returns the value of the "language" field in the mutation.
func (m *RepositoryMutation) Language() (r string, exists bool) {
	v := m.language
	if v == nil {
		return
	}
	return *v, true
}

// OldLanguage returns the old "language" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldLanguage(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLanguage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLanguage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLanguage: %w", err)
	}
	return oldValue.Language, nil
}

// ClearLanguage clears the value of the "language" field.
func (m *RepositoryMutation) ClearLanguage() {
	m.language = nil
	m.clearedFields[repository.FieldLanguage] = struct{}{}
}

// LanguageCleared returns if the "language" field was cleared in this mutation.
func (m *RepositoryMutation) LanguageCleared() bool {
	_, ok := m.clearedFields[repository.FieldLanguage]
	return ok
}

// ResetLanguage resets all changes to the "language" field.
func (m *RepositoryMutation) ResetLanguage() {
	m.language = nil
	delete(m.clearedFields, repository.FieldLanguage)
}

// SetHTMLURL sets the "html_url" field.
func (m *RepositoryMutation) SetHTMLURL(s string) {
	m.html_url = &s
}

// HTMLURL returns the value of the "html_url" field in the mutation.
func (m *RepositoryMutation) HTMLURL() (r string, exists bool) {
	v := m.html_url
	if v == nil {
		return
	}
	return *v, true
}

// OldHTMLURL returns the old "html_url" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldHTMLURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHTMLURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHTMLURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHTMLURL: %w", err)
	}
	return oldValue.HTMLURL, nil
}

// ResetHTMLURL resets all changes to the "html_url" field.
func (m *RepositoryMutation) ResetHTMLURL() {
	m.html_url = nil
}

// SetNotes sets the "notes" field.
func (m *RepositoryMutation) SetNotes(s string) {
	m.notes = &s
}

// Notes returns the value of the "notes" field in the mutation.
func (m *RepositoryMutation) Notes() (r string, exists bool) {
	v := m.notes
	if v == nil {
		return
	}
	return *v, true
}

// OldNotes returns the old "notes" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldNotes(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotes: %w", err)
	}
	return oldValue.Notes, nil
}

// ResetNotes resets all changes to the "notes" field.
func (m *RepositoryMutation) ResetNotes() {
	m.notes = nil
}

// SetFetchedAt sets the "fetched_at" field.
func (m *RepositoryMutation) SetFetchedAt(t time.Time) {
	m.fetched_at = &t
}

// FetchedAt returns the value of the "fetched_at" field in the mutation.
func (m *RepositoryMutation) FetchedAt() (r time.Time, exists bool) {
	v := m.fetched_at
	if v == nil {
		return
	}
	return *v, true
}

// OldFetchedAt returns the old "fetched_at" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldFetchedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFetchedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFetchedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFetchedAt: %w", err)
	}
	return oldValue.FetchedAt, nil
}

// ResetFetchedAt resets all changes to the "fetched_at" field.
func (m *RepositoryMutation) ResetFetchedAt() {
	m.fetched_at = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *RepositoryMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RepositoryMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RepositoryMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *RepositoryMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *RepositoryMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Repository entity.
// If the Repository object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RepositoryMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *RepositoryMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddRefreshJobIDs adds the "refresh_jobs" edge to the RefreshBatchJob entity by ids.
func (m *RepositoryMutation) AddRefreshJobIDs(ids ...uuid.UUID) {
	if m.refresh_jobs == nil {
		m.refresh_jobs = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.refresh_jobs[ids[i]] = struct{}{}
	}
}

// ClearRefreshJobs clears the "refresh_jobs" edge to the RefreshBatchJob entity.
func (m *RepositoryMutation) ClearRefreshJobs() {
	m.clearedrefresh_jobs = true
}

// RefreshJobsCleared reports if the "refresh_jobs" edge to the RefreshBatchJob entity was cleared.
func (m *RepositoryMutation) RefreshJobsCleared() bool {
	return m.clearedrefresh_jobs
}

// RemoveRefreshJobIDs removes the "refresh_jobs" edge to the RefreshBatchJob entity by IDs.
func (m *RepositoryMutation) RemoveRefreshJobIDs(ids ...uuid.UUID) {
	if m.removedrefresh_jobs == nil {
		m.removedrefresh_jobs = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.refresh_jobs, ids[i])
		m.removedrefresh_jobs[ids[i]] = struct{}{}
	}
}

// RemovedRefreshJobs returns the removed IDs of the "refresh_jobs" edge to the RefreshBatchJob entity.
func (m *RepositoryMutation) RemovedRefreshJobsIDs() (ids []uuid.UUID) {
	for id := range m.removedrefresh_jobs {
		ids = append(ids, id)
	}
	return
}

// RefreshJobsIDs returns the "refresh_jobs" edge IDs in the mutation.
func (m *RepositoryMutation) RefreshJobsIDs() (ids []uuid.UUID) {
	for id := range m.refresh_jobs {
		ids = append(ids, id)
	}
	return
}

// ResetRefreshJobs resets all changes to the "refresh_jobs" edge.
func (m *RepositoryMutation) ResetRefreshJobs() {
	m.refresh_jobs = nil
	m.clearedrefresh_jobs = false
	m.removedrefresh_jobs = nil
}

// Where appends a list predicates to the RepositoryMutation builder.
func (m *RepositoryMutation) Where(ps ...predicate.Repository) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RepositoryMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RepositoryMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Repository, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RepositoryMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RepositoryMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Repository).
func (m *RepositoryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RepositoryMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.owner != nil {
		fields = append(fields, repository.FieldOwner)
	}
	if m.name != nil {
		fields = append(fields, repository.FieldName)
	}
	if m.full_name != nil {
		fields = append(fields, repository.FieldFullName)
	}
	if m.description != nil {
		fields = append(fields, repository.FieldDescription)
	}
	if m.stars != nil {
		fields = append(fields, repository.FieldStars)
	}
	if m.language != nil {
		fields = append(fields, repository.FieldLanguage)
	}
	if m.html_url != nil {
		fields = append(fields, repository.FieldHTMLURL)
	}
	if m.notes != nil {
		fields = append(fields, repository.FieldNotes)
	}
	if m.fetched_at != nil {
		fields = append(fields, repository.FieldFetchedAt)
	}
	if m.created_at != nil {
		fields = append(fields, repository.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, repository.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RepositoryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case repository.FieldOwner:
		return m.Owner()
	case repository.FieldName:
		return m.Name()
	case repository.FieldFullName:
		return m.FullName()
	case repository.FieldDescription:
		return m.Description()
	case repository.FieldStars:
		return m.Stars()
	case repository.FieldLanguage:
		return m.Language()
	case repository.FieldHTMLURL:
		return m.HTMLURL()
	case repository.FieldNotes:
		return m.Notes()
	case repository.FieldFetchedAt:
		return m.FetchedAt()
	case repository.FieldCreatedAt:
		return m.CreatedAt()
	case repository.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RepositoryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case repository.FieldOwner:
		return m.OldOwner(ctx)
	case repository.FieldName:
		return m.OldName(ctx)
	case repository.FieldFullName:
		return m.OldFullName(ctx)
	case repository.FieldDescription:
		return m.OldDescription(ctx)
	case repository.FieldStars:
		return m.OldStars(ctx)
	case repository.FieldLanguage:
		return m.OldLanguage(ctx)
	case repository.FieldHTMLURL:
		return m.OldHTMLURL(ctx)
	case repository.FieldNotes:
		return m.OldNotes(ctx)
	case repository.FieldFetchedAt:
		return m.OldFetchedAt(ctx)
	case repository.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case repository.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Repository field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RepositoryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case repository.FieldOwner:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOwner(v)
		return nil
	case repository.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case repository.FieldFullName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFullName(v)
		return nil
	case repository.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case repository.FieldStars:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStars(v)
		return nil
	case repository.FieldLanguage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLanguage(v)
		return nil
	case repository.FieldHTMLURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHTMLURL(v)
		return nil
	case repository.FieldNotes:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotes(v)
		return nil
	case repository.FieldFetchedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFetchedAt(v)
		return nil
	case repository.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case repository.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Repository field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RepositoryMutation) AddedFields() []string {
	var fields []string
	if m.addstars != nil {
		fields = append(fields, repository.FieldStars)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RepositoryMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case repository.FieldStars:
		return m.AddedStars()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RepositoryMutation) AddField(name string, value ent.Value) error {
	switch name {
	case repository.FieldStars:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStars(v)
		return nil
	}
	return fmt.Errorf("unknown Repository numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RepositoryMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(repository.FieldDescription) {
		fields = append(fields, repository.FieldDescription)
	}
	if m.FieldCleared(repository.FieldLanguage) {
		fields = append(fields, repository.FieldLanguage)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RepositoryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RepositoryMutation) ClearField(name string) error {
	switch name {
	case repository.FieldDescription:
		m.ClearDescription()
		return nil
	case repository.FieldLanguage:
		m.ClearLanguage()
		return nil
	}
	return fmt.Errorf("unknown Repository nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RepositoryMutation) ResetField(name string) error {
	switch name {
	case repository.FieldOwner:
		m.ResetOwner()
		return nil
	case repository.FieldName:
		m.ResetName()
		return nil
	case repository.FieldFullName:
		m.ResetFullName()
		return nil
	case repository.FieldDescription:
		m.ResetDescription()
		return nil
	case repository.FieldStars:
		m.ResetStars()
		return nil
	case repository.FieldLanguage:
		m.ResetLanguage()
		return nil
	case repository.FieldHTMLURL:
		m.ResetHTMLURL()
		return nil
	case repository.FieldNotes:
		m.ResetNotes()
		return nil
	case repository.FieldFetchedAt:
		m.ResetFetchedAt()
		return nil
	case repository.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case repository.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Repository field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RepositoryMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.refresh_jobs != nil {
		edges = append(edges, repository.EdgeRefreshJobs)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RepositoryMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case repository.EdgeRefreshJobs:
		ids := make([]ent.Value, 0, len(m.refresh_jobs))
		for id := range m.refresh_jobs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RepositoryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedrefresh_jobs != nil {
		edges = append(edges, repository.EdgeRefreshJobs)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RepositoryMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case repository.EdgeRefreshJobs:
		ids := make([]ent.Value, 0, len(m.removedrefresh_jobs))
		for id := range m.removedrefresh_jobs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RepositoryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedrefresh_jobs {
		edges = append(edges, repository.EdgeRefreshJobs)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RepositoryMutation) EdgeCleared(name string) bool {
	switch name {
	case repository.EdgeRefreshJobs:
		return m.clearedrefresh_jobs
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RepositoryMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Repository unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RepositoryMutation) ResetEdge(name string) error {
	switch name {
	case repository.EdgeRefreshJobs:
		m.ResetRefreshJobs()
		return nil
	}
	return fmt.Errorf("unknown Repository edge %s", name)
}
