// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PavaoZornija1/github-tracker/internal/ent/predicate"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatch"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
	"github.com/PavaoZornija1/github-tracker/internal/ent/repository"
	"github.com/google/uuid"
)

// RefreshBatchJobQuery is the builder for querying RefreshBatchJob entities.
type RefreshBatchJobQuery struct {
	config
	ctx            *QueryContext
	order          []refreshbatchjob.OrderOption
	inters         []Interceptor
	predicates     []predicate.RefreshBatchJob
	withBatch      *RefreshBatchQuery
	withRepository *RepositoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RefreshBatchJobQuery builder.
func (_q *RefreshBatchJobQuery) Where(ps ...predicate.RefreshBatchJob) *RefreshBatchJobQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RefreshBatchJobQuery) Limit(limit int) *RefreshBatchJobQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RefreshBatchJobQuery) Offset(offset int) *RefreshBatchJobQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RefreshBatchJobQuery) Unique(unique bool) *RefreshBatchJobQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RefreshBatchJobQuery) Order(o ...refreshbatchjob.OrderOption) *RefreshBatchJobQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBatch chains the current query on the "batch" edge.
func (_q *RefreshBatchJobQuery) QueryBatch() *RefreshBatchQuery {
	query := (&RefreshBatchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(refreshbatchjob.Table, refreshbatchjob.FieldID, selector),
			sqlgraph.To(refreshbatch.Table, refreshbatch.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, refreshbatchjob.BatchTable, refreshbatchjob.BatchColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRepository chains the current query on the "repository" edge.
func (_q *RefreshBatchJobQuery) QueryRepository() *RepositoryQuery {
	query := (&RepositoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(refreshbatchjob.Table, refreshbatchjob.FieldID, selector),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, refreshbatchjob.RepositoryTable, refreshbatchjob.RepositoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RefreshBatchJob entity from the query.
// Returns a *NotFoundError when no RefreshBatchJob was found.
func (_q *RefreshBatchJobQuery) First(ctx context.Context) (*RefreshBatchJob, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{refreshbatchjob.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RefreshBatchJobQuery) FirstX(ctx context.Context) *RefreshBatchJob {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RefreshBatchJob ID from the query.
// Returns a *NotFoundError when no RefreshBatchJob ID was found.
func (_q *RefreshBatchJobQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{refreshbatchjob.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RefreshBatchJobQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RefreshBatchJob entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RefreshBatchJob entity is found.
// Returns a *NotFoundError when no RefreshBatchJob entities are found.
func (_q *RefreshBatchJobQuery) Only(ctx context.Context) (*RefreshBatchJob, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{refreshbatchjob.Label}
	default:
		return nil, &NotSingularError{refreshbatchjob.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RefreshBatchJobQuery) OnlyX(ctx context.Context) *RefreshBatchJob {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RefreshBatchJob ID in the query.
// Returns a *NotSingularError when more than one RefreshBatchJob ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RefreshBatchJobQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{refreshbatchjob.Label}
	default:
		err = &NotSingularError{refreshbatchjob.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RefreshBatchJobQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RefreshBatchJobs.
func (_q *RefreshBatchJobQuery) All(ctx context.Context) ([]*RefreshBatchJob, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RefreshBatchJob, *RefreshBatchJobQuery]()
	return withInterceptors[[]*RefreshBatchJob](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RefreshBatchJobQuery) AllX(ctx context.Context) []*RefreshBatchJob {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RefreshBatchJob IDs.
func (_q *RefreshBatchJobQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(refreshbatchjob.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RefreshBatchJobQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RefreshBatchJobQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RefreshBatchJobQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RefreshBatchJobQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RefreshBatchJobQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RefreshBatchJobQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RefreshBatchJobQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RefreshBatchJobQuery) Clone() *RefreshBatchJobQuery {
	if _q == nil {
		return nil
	}
	return &RefreshBatchJobQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]refreshbatchjob.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.RefreshBatchJob{}, _q.predicates...),
		withBatch:      _q.withBatch.Clone(),
		withRepository: _q.withRepository.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBatch tells the query-builder to eager-load the nodes that are connected to
// the "batch" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RefreshBatchJobQuery) WithBatch(opts ...func(*RefreshBatchQuery)) *RefreshBatchJobQuery {
	query := (&RefreshBatchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBatch = query
	return _q
}

// WithRepository tells the query-builder to eager-load the nodes that are connected to
// the "repository" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RefreshBatchJobQuery) WithRepository(opts ...func(*RepositoryQuery)) *RefreshBatchJobQuery {
	query := (&RepositoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRepository = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BatchID uuid.UUID `json:"batch_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RefreshBatchJob.Query().
//		GroupBy(refreshbatchjob.FieldBatchID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RefreshBatchJobQuery) GroupBy(field string, fields ...string) *RefreshBatchJobGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RefreshBatchJobGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = refreshbatchjob.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BatchID uuid.UUID `json:"batch_id,omitempty"`
//	}
//
//	client.RefreshBatchJob.Query().
//		Select(refreshbatchjob.FieldBatchID).
//		Scan(ctx, &v)
func (_q *RefreshBatchJobQuery) Select(fields ...string) *RefreshBatchJobSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RefreshBatchJobSelect{RefreshBatchJobQuery: _q}
	sbuild.label = refreshbatchjob.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RefreshBatchJobSelect configured with the given aggregations.
func (_q *RefreshBatchJobQuery) Aggregate(fns ...AggregateFunc) *RefreshBatchJobSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RefreshBatchJobQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !refreshbatchjob.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RefreshBatchJobQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RefreshBatchJob, error) {
	var (
		nodes       = []*RefreshBatchJob{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withBatch != nil,
			_q.withRepository != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RefreshBatchJob).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RefreshBatchJob{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBatch; query != nil {
		if err := _q.loadBatch(ctx, query, nodes, nil,
			func(n *RefreshBatchJob, e *RefreshBatch) { n.Edges.Batch = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRepository; query != nil {
		if err := _q.loadRepository(ctx, query, nodes, nil,
			func(n *RefreshBatchJob, e *Repository) { n.Edges.Repository = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RefreshBatchJobQuery) loadBatch(ctx context.Context, query *RefreshBatchQuery, nodes []*RefreshBatchJob, init func(*RefreshBatchJob), assign func(*RefreshBatchJob, *RefreshBatch)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*RefreshBatchJob)
	for i := range nodes {
		fk := nodes[i].BatchID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(refreshbatch.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "batch_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RefreshBatchJobQuery) loadRepository(ctx context.Context, query *RepositoryQuery, nodes []*RefreshBatchJob, init func(*RefreshBatchJob), assign func(*RefreshBatchJob, *Repository)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*RefreshBatchJob)
	for i := range nodes {
		fk := nodes[i].RepoID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(repository.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repo_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *RefreshBatchJobQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RefreshBatchJobQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(refreshbatchjob.Table, refreshbatchjob.Columns, sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refreshbatchjob.FieldID)
		for i := range fields {
			if fields[i] != refreshbatchjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withBatch != nil {
			_spec.Node.AddColumnOnce(refreshbatchjob.FieldBatchID)
		}
		if _q.withRepository != nil {
			_spec.Node.AddColumnOnce(refreshbatchjob.FieldRepoID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RefreshBatchJobQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(refreshbatchjob.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = refreshbatchjob.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RefreshBatchJobGroupBy is the group-by builder for RefreshBatchJob entities.
type RefreshBatchJobGroupBy struct {
	selector
	build *RefreshBatchJobQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RefreshBatchJobGroupBy) Aggregate(fns ...AggregateFunc) *RefreshBatchJobGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RefreshBatchJobGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RefreshBatchJobQuery, *RefreshBatchJobGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RefreshBatchJobGroupBy) sqlScan(ctx context.Context, root *RefreshBatchJobQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RefreshBatchJobSelect is the builder for selecting fields of RefreshBatchJob entities.
type RefreshBatchJobSelect struct {
	*RefreshBatchJobQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RefreshBatchJobSelect) Aggregate(fns ...AggregateFunc) *RefreshBatchJobSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RefreshBatchJobSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RefreshBatchJobQuery, *RefreshBatchJobSelect](ctx, _s.RefreshBatchJobQuery, _s, _s.inters, v)
}

func (_s *RefreshBatchJobSelect) sqlScan(ctx context.Context, root *RefreshBatchJobQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
