// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PavaoZornija1/github-tracker/internal/ent/predicate"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatch"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
	"github.com/google/uuid"
)

// RefreshBatchUpdate is the builder for updating RefreshBatch entities.
type RefreshBatchUpdate struct {
	config
	hooks    []Hook
	mutation *RefreshBatchMutation
}

// Where appends a list predicates to the RefreshBatchUpdate builder.
func (_u *RefreshBatchUpdate) Where(ps ...predicate.RefreshBatch) *RefreshBatchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefreshBatchUpdate) SetUpdatedAt(v time.Time) *RefreshBatchUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddJobIDs adds the "jobs" edge to the RefreshBatchJob entity by IDs.
func (_u *RefreshBatchUpdate) AddJobIDs(ids ...uuid.UUID) *RefreshBatchUpdate {
	_u.mutation.AddJobIDs(ids...)
	return _u
}

// AddJobs adds the "jobs" edges to the RefreshBatchJob entity.
func (_u *RefreshBatchUpdate) AddJobs(v ...*RefreshBatchJob) *RefreshBatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobIDs(ids...)
}

// Mutation returns the RefreshBatchMutation object of the builder.
func (_u *RefreshBatchUpdate) Mutation() *RefreshBatchMutation {
	return _u.mutation
}

// ClearJobs clears all "jobs" edges to the RefreshBatchJob entity.
func (_u *RefreshBatchUpdate) ClearJobs() *RefreshBatchUpdate {
	_u.mutation.ClearJobs()
	return _u
}

// RemoveJobIDs removes the "jobs" edge to RefreshBatchJob entities by IDs.
func (_u *RefreshBatchUpdate) RemoveJobIDs(ids ...uuid.UUID) *RefreshBatchUpdate {
	_u.mutation.RemoveJobIDs(ids...)
	return _u
}

// RemoveJobs removes "jobs" edges to RefreshBatchJob entities.
func (_u *RefreshBatchUpdate) RemoveJobs(v ...*RefreshBatchJob) *RefreshBatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RefreshBatchUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefreshBatchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RefreshBatchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefreshBatchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefreshBatchUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := refreshbatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RefreshBatchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(refreshbatch.Table, refreshbatch.Columns, sqlgraph.NewFieldSpec(refreshbatch.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(refreshbatch.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   refreshbatch.JobsTable,
			Columns: []string{refreshbatch.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobsIDs(); len(nodes) > 0 && !_u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   refreshbatch.JobsTable,
			Columns: []string{refreshbatch.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   refreshbatch.JobsTable,
			Columns: []string{refreshbatch.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshbatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RefreshBatchUpdateOne is the builder for updating a single RefreshBatch entity.
type RefreshBatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefreshBatchMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefreshBatchUpdateOne) SetUpdatedAt(v time.Time) *RefreshBatchUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddJobIDs adds the "jobs" edge to the RefreshBatchJob entity by IDs.
func (_u *RefreshBatchUpdateOne) AddJobIDs(ids ...uuid.UUID) *RefreshBatchUpdateOne {
	_u.mutation.AddJobIDs(ids...)
	return _u
}

// AddJobs adds the "jobs" edges to the RefreshBatchJob entity.
func (_u *RefreshBatchUpdateOne) AddJobs(v ...*RefreshBatchJob) *RefreshBatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobIDs(ids...)
}

// Mutation returns the RefreshBatchMutation object of the builder.
func (_u *RefreshBatchUpdateOne) Mutation() *RefreshBatchMutation {
	return _u.mutation
}

// ClearJobs clears all "jobs" edges to the RefreshBatchJob entity.
func (_u *RefreshBatchUpdateOne) ClearJobs() *RefreshBatchUpdateOne {
	_u.mutation.ClearJobs()
	return _u
}

// RemoveJobIDs removes the "jobs" edge to RefreshBatchJob entities by IDs.
func (_u *RefreshBatchUpdateOne) RemoveJobIDs(ids ...uuid.UUID) *RefreshBatchUpdateOne {
	_u.mutation.RemoveJobIDs(ids...)
	return _u
}

// RemoveJobs removes "jobs" edges to RefreshBatchJob entities.
func (_u *RefreshBatchUpdateOne) RemoveJobs(v ...*RefreshBatchJob) *RefreshBatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobIDs(ids...)
}

// Where appends a list predicates to the RefreshBatchUpdate builder.
func (_u *RefreshBatchUpdateOne) Where(ps ...predicate.RefreshBatch) *RefreshBatchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RefreshBatchUpdateOne) Select(field string, fields ...string) *RefreshBatchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RefreshBatch entity.
func (_u *RefreshBatchUpdateOne) Save(ctx context.Context) (*RefreshBatch, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefreshBatchUpdateOne) SaveX(ctx context.Context) *RefreshBatch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RefreshBatchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefreshBatchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefreshBatchUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := refreshbatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RefreshBatchUpdateOne) sqlSave(ctx context.Context) (_node *RefreshBatch, err error) {
	_spec := sqlgraph.NewUpdateSpec(refreshbatch.Table, refreshbatch.Columns, sqlgraph.NewFieldSpec(refreshbatch.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefreshBatch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refreshbatch.FieldID)
		for _, f := range fields {
			if !refreshbatch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refreshbatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(refreshbatch.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   refreshbatch.JobsTable,
			Columns: []string{refreshbatch.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobsIDs(); len(nodes) > 0 && !_u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   refreshbatch.JobsTable,
			Columns: []string{refreshbatch.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   refreshbatch.JobsTable,
			Columns: []string{refreshbatch.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RefreshBatch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshbatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
