// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PavaoZornija1/github-tracker/ent/schema"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatch"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
	"github.com/PavaoZornija1/github-tracker/internal/ent/repository"
	"github.com/google/uuid"
)

// RefreshBatchJob is the model entity for the RefreshBatchJob schema.
type RefreshBatchJob struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// BatchID holds the value of the "batch_id" field.
	BatchID uuid.UUID `json:"batch_id,omitempty"`
	// RepoID holds the value of the "repo_id" field.
	RepoID uuid.UUID `json:"repo_id,omitempty"`
	// Status holds the value of the "status" field.
	Status schema.RefreshJobStatus `json:"status,omitempty"`
	// Attempt holds the value of the "attempt" field.
	Attempt int `json:"attempt,omitempty"`
	// ErrorReason holds the value of the "error_reason" field.
	ErrorReason *string `json:"error_reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RefreshBatchJobQuery when eager-loading is set.
	Edges        RefreshBatchJobEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RefreshBatchJobEdges holds the relations/edges for other nodes in the graph.
type RefreshBatchJobEdges struct {
	// Batch holds the value of the batch edge.
	Batch *RefreshBatch `json:"batch,omitempty"`
	// Repository holds the value of the repository edge.
	Repository *Repository `json:"repository,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BatchOrErr returns the Batch value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RefreshBatchJobEdges) BatchOrErr() (*RefreshBatch, error) {
	if e.Batch != nil {
		return e.Batch, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: refreshbatch.Label}
	}
	return nil, &NotLoadedError{edge: "batch"}
}

// RepositoryOrErr returns the Repository value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RefreshBatchJobEdges) RepositoryOrErr() (*Repository, error) {
	if e.Repository != nil {
		return e.Repository, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: repository.Label}
	}
	return nil, &NotLoadedError{edge: "repository"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RefreshBatchJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case refreshbatchjob.FieldAttempt:
			values[i] = new(sql.NullInt64)
		case refreshbatchjob.FieldStatus, refreshbatchjob.FieldErrorReason:
			values[i] = new(sql.NullString)
		case refreshbatchjob.FieldCreatedAt, refreshbatchjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case refreshbatchjob.FieldID, refreshbatchjob.FieldBatchID, refreshbatchjob.FieldRepoID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RefreshBatchJob fields.
func (_m *RefreshBatchJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case refreshbatchjob.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case refreshbatchjob.FieldBatchID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field batch_id", values[i])
			} else if value != nil {
				_m.BatchID = *value
			}
		case refreshbatchjob.FieldRepoID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field repo_id", values[i])
			} else if value != nil {
				_m.RepoID = *value
			}
		case refreshbatchjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = schema.RefreshJobStatus(value.String)
			}
		case refreshbatchjob.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				_m.Attempt = int(value.Int64)
			}
		case refreshbatchjob.FieldErrorReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_reason", values[i])
			} else if value.Valid {
				_m.ErrorReason = new(string)
				*_m.ErrorReason = value.String
			}
		case refreshbatchjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case refreshbatchjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RefreshBatchJob.
// This includes values selected through modifiers, order, etc.
func (_m *RefreshBatchJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBatch queries the "batch" edge of the RefreshBatchJob entity.
func (_m *RefreshBatchJob) QueryBatch() *RefreshBatchQuery {
	return NewRefreshBatchJobClient(_m.config).QueryBatch(_m)
}

// QueryRepository queries the "repository" edge of the RefreshBatchJob entity.
func (_m *RefreshBatchJob) QueryRepository() *RepositoryQuery {
	return NewRefreshBatchJobClient(_m.config).QueryRepository(_m)
}

// Update returns a builder for updating this RefreshBatchJob.
// Note that you need to call RefreshBatchJob.Unwrap() before calling this method if this RefreshBatchJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RefreshBatchJob) Update() *RefreshBatchJobUpdateOne {
	return NewRefreshBatchJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RefreshBatchJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RefreshBatchJob) Unwrap() *RefreshBatchJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RefreshBatchJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RefreshBatchJob) String() string {
	var builder strings.Builder
	builder.WriteString("RefreshBatchJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("batch_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchID))
	builder.WriteString(", ")
	builder.WriteString("repo_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RepoID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempt))
	builder.WriteString(", ")
	if v := _m.ErrorReason; v != nil {
		builder.WriteString("error_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RefreshBatchJobs is a parsable slice of RefreshBatchJob.
type RefreshBatchJobs []*RefreshBatchJob
