// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PavaoZornija1/github-tracker/ent/schema"
	"github.com/PavaoZornija1/github-tracker/internal/ent/predicate"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatch"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
	"github.com/PavaoZornija1/github-tracker/internal/ent/repository"
	"github.com/google/uuid"
)

// RefreshBatchJobUpdate is the builder for updating RefreshBatchJob entities.
type RefreshBatchJobUpdate struct {
	config
	hooks    []Hook
	mutation *RefreshBatchJobMutation
}

// Where appends a list predicates to the RefreshBatchJobUpdate builder.
func (_u *RefreshBatchJobUpdate) Where(ps ...predicate.RefreshBatchJob) *RefreshBatchJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *RefreshBatchJobUpdate) SetBatchID(v uuid.UUID) *RefreshBatchJobUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *RefreshBatchJobUpdate) SetNillableBatchID(v *uuid.UUID) *RefreshBatchJobUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetRepoID sets the "repo_id" field.
func (_u *RefreshBatchJobUpdate) SetRepoID(v uuid.UUID) *RefreshBatchJobUpdate {
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *RefreshBatchJobUpdate) SetNillableRepoID(v *uuid.UUID) *RefreshBatchJobUpdate {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RefreshBatchJobUpdate) SetStatus(v schema.RefreshJobStatus) *RefreshBatchJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RefreshBatchJobUpdate) SetNillableStatus(v *schema.RefreshJobStatus) *RefreshBatchJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *RefreshBatchJobUpdate) SetAttempt(v int) *RefreshBatchJobUpdate {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *RefreshBatchJobUpdate) SetNillableAttempt(v *int) *RefreshBatchJobUpdate {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *RefreshBatchJobUpdate) AddAttempt(v int) *RefreshBatchJobUpdate {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetErrorReason sets the "error_reason" field.
func (_u *RefreshBatchJobUpdate) SetErrorReason(v string) *RefreshBatchJobUpdate {
	_u.mutation.SetErrorReason(v)
	return _u
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_u *RefreshBatchJobUpdate) SetNillableErrorReason(v *string) *RefreshBatchJobUpdate {
	if v != nil {
		_u.SetErrorReason(*v)
	}
	return _u
}

// ClearErrorReason clears the value of the "error_reason" field.
func (_u *RefreshBatchJobUpdate) ClearErrorReason() *RefreshBatchJobUpdate {
	_u.mutation.ClearErrorReason()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefreshBatchJobUpdate) SetUpdatedAt(v time.Time) *RefreshBatchJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBatch sets the "batch" edge to the RefreshBatch entity.
func (_u *RefreshBatchJobUpdate) SetBatch(v *RefreshBatch) *RefreshBatchJobUpdate {
	return _u.SetBatchID(v.ID)
}

// SetRepositoryID sets the "repository" edge to the Repository entity by ID.
func (_u *RefreshBatchJobUpdate) SetRepositoryID(id uuid.UUID) *RefreshBatchJobUpdate {
	_u.mutation.SetRepositoryID(id)
	return _u
}

// SetRepository sets the "repository" edge to the Repository entity.
func (_u *RefreshBatchJobUpdate) SetRepository(v *Repository) *RefreshBatchJobUpdate {
	return _u.SetRepositoryID(v.ID)
}

// Mutation returns the RefreshBatchJobMutation object of the builder.
func (_u *RefreshBatchJobUpdate) Mutation() *RefreshBatchJobMutation {
	return _u.mutation
}

// ClearBatch clears the "batch" edge to the RefreshBatch entity.
func (_u *RefreshBatchJobUpdate) ClearBatch() *RefreshBatchJobUpdate {
	_u.mutation.ClearBatch()
	return _u
}

// ClearRepository clears the "repository" edge to the Repository entity.
func (_u *RefreshBatchJobUpdate) ClearRepository() *RefreshBatchJobUpdate {
	_u.mutation.ClearRepository()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RefreshBatchJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefreshBatchJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RefreshBatchJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefreshBatchJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefreshBatchJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := refreshbatchjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RefreshBatchJobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := refreshbatchjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RefreshBatchJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempt(); ok {
		if err := refreshbatchjob.AttemptValidator(v); err != nil {
			return &ValidationError{Name: "attempt", err: fmt.Errorf(`ent: validator failed for field "RefreshBatchJob.attempt": %w`, err)}
		}
	}
	if _u.mutation.BatchCleared() && len(_u.mutation.BatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RefreshBatchJob.batch"`)
	}
	if _u.mutation.RepositoryCleared() && len(_u.mutation.RepositoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RefreshBatchJob.repository"`)
	}
	return nil
}

func (_u *RefreshBatchJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refreshbatchjob.Table, refreshbatchjob.Columns, sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(refreshbatchjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(refreshbatchjob.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(refreshbatchjob.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorReason(); ok {
		_spec.SetField(refreshbatchjob.FieldErrorReason, field.TypeString, value)
	}
	if _u.mutation.ErrorReasonCleared() {
		_spec.ClearField(refreshbatchjob.FieldErrorReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(refreshbatchjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.BatchTable,
			Columns: []string{refreshbatchjob.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.BatchTable,
			Columns: []string{refreshbatchjob.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepositoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.RepositoryTable,
			Columns: []string{refreshbatchjob.RepositoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepositoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.RepositoryTable,
			Columns: []string{refreshbatchjob.RepositoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshbatchjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RefreshBatchJobUpdateOne is the builder for updating a single RefreshBatchJob entity.
type RefreshBatchJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefreshBatchJobMutation
}

// SetBatchID sets the "batch_id" field.
func (_u *RefreshBatchJobUpdateOne) SetBatchID(v uuid.UUID) *RefreshBatchJobUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *RefreshBatchJobUpdateOne) SetNillableBatchID(v *uuid.UUID) *RefreshBatchJobUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetRepoID sets the "repo_id" field.
func (_u *RefreshBatchJobUpdateOne) SetRepoID(v uuid.UUID) *RefreshBatchJobUpdateOne {
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *RefreshBatchJobUpdateOne) SetNillableRepoID(v *uuid.UUID) *RefreshBatchJobUpdateOne {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RefreshBatchJobUpdateOne) SetStatus(v schema.RefreshJobStatus) *RefreshBatchJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RefreshBatchJobUpdateOne) SetNillableStatus(v *schema.RefreshJobStatus) *RefreshBatchJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *RefreshBatchJobUpdateOne) SetAttempt(v int) *RefreshBatchJobUpdateOne {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *RefreshBatchJobUpdateOne) SetNillableAttempt(v *int) *RefreshBatchJobUpdateOne {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *RefreshBatchJobUpdateOne) AddAttempt(v int) *RefreshBatchJobUpdateOne {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetErrorReason sets the "error_reason" field.
func (_u *RefreshBatchJobUpdateOne) SetErrorReason(v string) *RefreshBatchJobUpdateOne {
	_u.mutation.SetErrorReason(v)
	return _u
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_u *RefreshBatchJobUpdateOne) SetNillableErrorReason(v *string) *RefreshBatchJobUpdateOne {
	if v != nil {
		_u.SetErrorReason(*v)
	}
	return _u
}

// ClearErrorReason clears the value of the "error_reason" field.
func (_u *RefreshBatchJobUpdateOne) ClearErrorReason() *RefreshBatchJobUpdateOne {
	_u.mutation.ClearErrorReason()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RefreshBatchJobUpdateOne) SetUpdatedAt(v time.Time) *RefreshBatchJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBatch sets the "batch" edge to the RefreshBatch entity.
func (_u *RefreshBatchJobUpdateOne) SetBatch(v *RefreshBatch) *RefreshBatchJobUpdateOne {
	return _u.SetBatchID(v.ID)
}

// SetRepositoryID sets the "repository" edge to the Repository entity by ID.
func (_u *RefreshBatchJobUpdateOne) SetRepositoryID(id uuid.UUID) *RefreshBatchJobUpdateOne {
	_u.mutation.SetRepositoryID(id)
	return _u
}

// SetRepository sets the "repository" edge to the Repository entity.
func (_u *RefreshBatchJobUpdateOne) SetRepository(v *Repository) *RefreshBatchJobUpdateOne {
	return _u.SetRepositoryID(v.ID)
}

// Mutation returns the RefreshBatchJobMutation object of the builder.
func (_u *RefreshBatchJobUpdateOne) Mutation() *RefreshBatchJobMutation {
	return _u.mutation
}

// ClearBatch clears the "batch" edge to the RefreshBatch entity.
func (_u *RefreshBatchJobUpdateOne) ClearBatch() *RefreshBatchJobUpdateOne {
	_u.mutation.ClearBatch()
	return _u
}

// ClearRepository clears the "repository" edge to the Repository entity.
func (_u *RefreshBatchJobUpdateOne) ClearRepository() *RefreshBatchJobUpdateOne {
	_u.mutation.ClearRepository()
	return _u
}

// Where appends a list predicates to the RefreshBatchJobUpdate builder.
func (_u *RefreshBatchJobUpdateOne) Where(ps ...predicate.RefreshBatchJob) *RefreshBatchJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RefreshBatchJobUpdateOne) Select(field string, fields ...string) *RefreshBatchJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RefreshBatchJob entity.
func (_u *RefreshBatchJobUpdateOne) Save(ctx context.Context) (*RefreshBatchJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefreshBatchJobUpdateOne) SaveX(ctx context.Context) *RefreshBatchJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RefreshBatchJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefreshBatchJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RefreshBatchJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := refreshbatchjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RefreshBatchJobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := refreshbatchjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RefreshBatchJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempt(); ok {
		if err := refreshbatchjob.AttemptValidator(v); err != nil {
			return &ValidationError{Name: "attempt", err: fmt.Errorf(`ent: validator failed for field "RefreshBatchJob.attempt": %w`, err)}
		}
	}
	if _u.mutation.BatchCleared() && len(_u.mutation.BatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RefreshBatchJob.batch"`)
	}
	if _u.mutation.RepositoryCleared() && len(_u.mutation.RepositoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RefreshBatchJob.repository"`)
	}
	return nil
}

func (_u *RefreshBatchJobUpdateOne) sqlSave(ctx context.Context) (_node *RefreshBatchJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refreshbatchjob.Table, refreshbatchjob.Columns, sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefreshBatchJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refreshbatchjob.FieldID)
		for _, f := range fields {
			if !refreshbatchjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refreshbatchjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(refreshbatchjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(refreshbatchjob.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(refreshbatchjob.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorReason(); ok {
		_spec.SetField(refreshbatchjob.FieldErrorReason, field.TypeString, value)
	}
	if _u.mutation.ErrorReasonCleared() {
		_spec.ClearField(refreshbatchjob.FieldErrorReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(refreshbatchjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.BatchTable,
			Columns: []string{refreshbatchjob.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.BatchTable,
			Columns: []string{refreshbatchjob.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepositoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.RepositoryTable,
			Columns: []string{refreshbatchjob.RepositoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepositoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.RepositoryTable,
			Columns: []string{refreshbatchjob.RepositoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RefreshBatchJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshbatchjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
