// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PavaoZornija1/github-tracker/ent/schema"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatch"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
	"github.com/PavaoZornija1/github-tracker/internal/ent/repository"
	"github.com/google/uuid"
)

// RefreshBatchJobCreate is the builder for creating a RefreshBatchJob entity.
type RefreshBatchJobCreate struct {
	config
	mutation *RefreshBatchJobMutation
	hooks    []Hook
}

// SetBatchID sets the "batch_id" field.
func (_c *RefreshBatchJobCreate) SetBatchID(v uuid.UUID) *RefreshBatchJobCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetRepoID sets the "repo_id" field.
func (_c *RefreshBatchJobCreate) SetRepoID(v uuid.UUID) *RefreshBatchJobCreate {
	_c.mutation.SetRepoID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RefreshBatchJobCreate) SetStatus(v schema.RefreshJobStatus) *RefreshBatchJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RefreshBatchJobCreate) SetNillableStatus(v *schema.RefreshJobStatus) *RefreshBatchJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttempt sets the "attempt" field.
func (_c *RefreshBatchJobCreate) SetAttempt(v int) *RefreshBatchJobCreate {
	_c.mutation.SetAttempt(v)
	return _c
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_c *RefreshBatchJobCreate) SetNillableAttempt(v *int) *RefreshBatchJobCreate {
	if v != nil {
		_c.SetAttempt(*v)
	}
	return _c
}

// SetErrorReason sets the "error_reason" field.
func (_c *RefreshBatchJobCreate) SetErrorReason(v string) *RefreshBatchJobCreate {
	_c.mutation.SetErrorReason(v)
	return _c
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_c *RefreshBatchJobCreate) SetNillableErrorReason(v *string) *RefreshBatchJobCreate {
	if v != nil {
		_c.SetErrorReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RefreshBatchJobCreate) SetCreatedAt(v time.Time) *RefreshBatchJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RefreshBatchJobCreate) SetNillableCreatedAt(v *time.Time) *RefreshBatchJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RefreshBatchJobCreate) SetUpdatedAt(v time.Time) *RefreshBatchJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RefreshBatchJobCreate) SetNillableUpdatedAt(v *time.Time) *RefreshBatchJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RefreshBatchJobCreate) SetID(v uuid.UUID) *RefreshBatchJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RefreshBatchJobCreate) SetNillableID(v *uuid.UUID) *RefreshBatchJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetBatch sets the "batch" edge to the RefreshBatch entity.
func (_c *RefreshBatchJobCreate) SetBatch(v *RefreshBatch) *RefreshBatchJobCreate {
	return _c.SetBatchID(v.ID)
}

// SetRepositoryID sets the "repository" edge to the Repository entity by ID.
func (_c *RefreshBatchJobCreate) SetRepositoryID(id uuid.UUID) *RefreshBatchJobCreate {
	_c.mutation.SetRepositoryID(id)
	return _c
}

// SetRepository sets the "repository" edge to the Repository entity.
func (_c *RefreshBatchJobCreate) SetRepository(v *Repository) *RefreshBatchJobCreate {
	return _c.SetRepositoryID(v.ID)
}

// Mutation returns the RefreshBatchJobMutation object of the builder.
func (_c *RefreshBatchJobCreate) Mutation() *RefreshBatchJobMutation {
	return _c.mutation
}

// Save creates the RefreshBatchJob in the database.
func (_c *RefreshBatchJobCreate) Save(ctx context.Context) (*RefreshBatchJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RefreshBatchJobCreate) SaveX(ctx context.Context) *RefreshBatchJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefreshBatchJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefreshBatchJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RefreshBatchJobCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := refreshbatchjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		v := refreshbatchjob.DefaultAttempt
		_c.mutation.SetAttempt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := refreshbatchjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := refreshbatchjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := refreshbatchjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RefreshBatchJobCreate) check() error {
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "RefreshBatchJob.batch_id"`)}
	}
	if _, ok := _c.mutation.RepoID(); !ok {
		return &ValidationError{Name: "repo_id", err: errors.New(`ent: missing required field "RefreshBatchJob.repo_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RefreshBatchJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := refreshbatchjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RefreshBatchJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required field "RefreshBatchJob.attempt"`)}
	}
	if v, ok := _c.mutation.Attempt(); ok {
		if err := refreshbatchjob.AttemptValidator(v); err != nil {
			return &ValidationError{Name: "attempt", err: fmt.Errorf(`ent: validator failed for field "RefreshBatchJob.attempt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RefreshBatchJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RefreshBatchJob.updated_at"`)}
	}
	if len(_c.mutation.BatchIDs()) == 0 {
		return &ValidationError{Name: "batch", err: errors.New(`ent: missing required edge "RefreshBatchJob.batch"`)}
	}
	if len(_c.mutation.RepositoryIDs()) == 0 {
		return &ValidationError{Name: "repository", err: errors.New(`ent: missing required edge "RefreshBatchJob.repository"`)}
	}
	return nil
}

func (_c *RefreshBatchJobCreate) sqlSave(ctx context.Context) (*RefreshBatchJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RefreshBatchJobCreate) createSpec() (*RefreshBatchJob, *sqlgraph.CreateSpec) {
	var (
		_node = &RefreshBatchJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(refreshbatchjob.Table, sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(refreshbatchjob.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Attempt(); ok {
		_spec.SetField(refreshbatchjob.FieldAttempt, field.TypeInt, value)
		_node.Attempt = value
	}
	if value, ok := _c.mutation.ErrorReason(); ok {
		_spec.SetField(refreshbatchjob.FieldErrorReason, field.TypeString, value)
		_node.ErrorReason = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(refreshbatchjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(refreshbatchjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.BatchTable,
			Columns: []string{refreshbatchjob.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BatchID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RepositoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refreshbatchjob.RepositoryTable,
			Columns: []string{refreshbatchjob.RepositoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RepoID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RefreshBatchJobCreateBulk is the builder for creating many RefreshBatchJob entities in bulk.
type RefreshBatchJobCreateBulk struct {
	config
	err      error
	builders []*RefreshBatchJobCreate
}

// Save creates the RefreshBatchJob entities in the database.
func (_c *RefreshBatchJobCreateBulk) Save(ctx context.Context) ([]*RefreshBatchJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RefreshBatchJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefreshBatchJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RefreshBatchJobCreateBulk) SaveX(ctx context.Context) []*RefreshBatchJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefreshBatchJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefreshBatchJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
