// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PavaoZornija1/github-tracker/internal/ent/predicate"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
)

// RefreshBatchJobDelete is the builder for deleting a RefreshBatchJob entity.
type RefreshBatchJobDelete struct {
	config
	hooks    []Hook
	mutation *RefreshBatchJobMutation
}

// Where appends a list predicates to the RefreshBatchJobDelete builder.
func (_d *RefreshBatchJobDelete) Where(ps ...predicate.RefreshBatchJob) *RefreshBatchJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RefreshBatchJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RefreshBatchJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RefreshBatchJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(refreshbatchjob.Table, sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RefreshBatchJobDeleteOne is the builder for deleting a single RefreshBatchJob entity.
type RefreshBatchJobDeleteOne struct {
	_d *RefreshBatchJobDelete
}

// Where appends a list predicates to the RefreshBatchJobDelete builder.
func (_d *RefreshBatchJobDeleteOne) Where(ps ...predicate.RefreshBatchJob) *RefreshBatchJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RefreshBatchJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{refreshbatchjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RefreshBatchJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
