// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PavaoZornija1/github-tracker/internal/ent/predicate"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
	"github.com/PavaoZornija1/github-tracker/internal/ent/repository"
	"github.com/google/uuid"
)

// RepositoryUpdate is the builder for updating Repository entities.
type RepositoryUpdate struct {
	config
	hooks    []Hook
	mutation *RepositoryMutation
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdate) Where(ps ...predicate.Repository) *RepositoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepositoryUpdate) SetOwner(v string) *RepositoryUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableOwner(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepositoryUpdate) SetName(v string) *RepositoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *RepositoryUpdate) SetFullName(v string) *RepositoryUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableFullName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RepositoryUpdate) SetDescription(v string) *RepositoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableDescription(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RepositoryUpdate) ClearDescription() *RepositoryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStars sets the "stars" field.
func (_u *RepositoryUpdate) SetStars(v int) *RepositoryUpdate {
	_u.mutation.ResetStars()
	_u.mutation.SetStars(v)
	return _u
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableStars(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetStars(*v)
	}
	return _u
}

// AddStars adds value to the "stars" field.
func (_u *RepositoryUpdate) AddStars(v int) *RepositoryUpdate {
	_u.mutation.AddStars(v)
	return _u
}

// SetLanguage sets the "language" field.
func (_u *RepositoryUpdate) SetLanguage(v string) *RepositoryUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLanguage(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *RepositoryUpdate) ClearLanguage() *RepositoryUpdate {
	_u.mutation.ClearLanguage()
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *RepositoryUpdate) SetHTMLURL(v string) *RepositoryUpdate {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableHTMLURL(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RepositoryUpdate) SetNotes(v string) *RepositoryUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableNotes(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *RepositoryUpdate) SetFetchedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableFetchedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdate) SetUpdatedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRefreshJobIDs adds the "refresh_jobs" edge to the RefreshBatchJob entity by IDs.
func (_u *RepositoryUpdate) AddRefreshJobIDs(ids ...uuid.UUID) *RepositoryUpdate {
	_u.mutation.AddRefreshJobIDs(ids...)
	return _u
}

// AddRefreshJobs adds the "refresh_jobs" edges to the RefreshBatchJob entity.
func (_u *RepositoryUpdate) AddRefreshJobs(v ...*RefreshBatchJob) *RepositoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRefreshJobIDs(ids...)
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdate) Mutation() *RepositoryMutation {
	return _u.mutation
}

// ClearRefreshJobs clears all "refresh_jobs" edges to the RefreshBatchJob entity.
func (_u *RepositoryUpdate) ClearRefreshJobs() *RepositoryUpdate {
	_u.mutation.ClearRefreshJobs()
	return _u
}

// RemoveRefreshJobIDs removes the "refresh_jobs" edge to RefreshBatchJob entities by IDs.
func (_u *RepositoryUpdate) RemoveRefreshJobIDs(ids ...uuid.UUID) *RepositoryUpdate {
	_u.mutation.RemoveRefreshJobIDs(ids...)
	return _u
}

// RemoveRefreshJobs removes "refresh_jobs" edges to RefreshBatchJob entities.
func (_u *RepositoryUpdate) RemoveRefreshJobs(v ...*RefreshBatchJob) *RepositoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRefreshJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepositoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepositoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepositoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repository.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepositoryUpdate) check() error {
	if v, ok := _u.mutation.Owner(); ok {
		if err := repository.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Repository.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := repository.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Repository.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := repository.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Repository.full_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stars(); ok {
		if err := repository.StarsValidator(v); err != nil {
			return &ValidationError{Name: "stars", err: fmt.Errorf(`ent: validator failed for field "Repository.stars": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTMLURL(); ok {
		if err := repository.HTMLURLValidator(v); err != nil {
			return &ValidationError{Name: "html_url", err: fmt.Errorf(`ent: validator failed for field "Repository.html_url": %w`, err)}
		}
	}
	return nil
}

func (_u *RepositoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repository.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(repository.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(repository.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Stars(); ok {
		_spec.SetField(repository.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStars(); ok {
		_spec.AddField(repository.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(repository.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(repository.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(repository.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(repository.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(repository.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RefreshJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.RefreshJobsTable,
			Columns: []string{repository.RefreshJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRefreshJobsIDs(); len(nodes) > 0 && !_u.mutation.RefreshJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.RefreshJobsTable,
			Columns: []string{repository.RefreshJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefreshJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.RefreshJobsTable,
			Columns: []string{repository.RefreshJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepositoryUpdateOne is the builder for updating a single Repository entity.
type RepositoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepositoryMutation
}

// SetOwner sets the "owner" field.
func (_u *RepositoryUpdateOne) SetOwner(v string) *RepositoryUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableOwner(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepositoryUpdateOne) SetName(v string) *RepositoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *RepositoryUpdateOne) SetFullName(v string) *RepositoryUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableFullName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RepositoryUpdateOne) SetDescription(v string) *RepositoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableDescription(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RepositoryUpdateOne) ClearDescription() *RepositoryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStars sets the "stars" field.
func (_u *RepositoryUpdateOne) SetStars(v int) *RepositoryUpdateOne {
	_u.mutation.ResetStars()
	_u.mutation.SetStars(v)
	return _u
}

// SetNillableStars sets the "stars" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableStars(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetStars(*v)
	}
	return _u
}

// AddStars adds value to the "stars" field.
func (_u *RepositoryUpdateOne) AddStars(v int) *RepositoryUpdateOne {
	_u.mutation.AddStars(v)
	return _u
}

// SetLanguage sets the "language" field.
func (_u *RepositoryUpdateOne) SetLanguage(v string) *RepositoryUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLanguage(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *RepositoryUpdateOne) ClearLanguage() *RepositoryUpdateOne {
	_u.mutation.ClearLanguage()
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *RepositoryUpdateOne) SetHTMLURL(v string) *RepositoryUpdateOne {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableHTMLURL(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RepositoryUpdateOne) SetNotes(v string) *RepositoryUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableNotes(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetFetchedAt sets the "fetched_at" field.
func (_u *RepositoryUpdateOne) SetFetchedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetFetchedAt(v)
	return _u
}

// SetNillableFetchedAt sets the "fetched_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableFetchedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetFetchedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdateOne) SetUpdatedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRefreshJobIDs adds the "refresh_jobs" edge to the RefreshBatchJob entity by IDs.
func (_u *RepositoryUpdateOne) AddRefreshJobIDs(ids ...uuid.UUID) *RepositoryUpdateOne {
	_u.mutation.AddRefreshJobIDs(ids...)
	return _u
}

// AddRefreshJobs adds the "refresh_jobs" edges to the RefreshBatchJob entity.
func (_u *RepositoryUpdateOne) AddRefreshJobs(v ...*RefreshBatchJob) *RepositoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRefreshJobIDs(ids...)
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdateOne) Mutation() *RepositoryMutation {
	return _u.mutation
}

// ClearRefreshJobs clears all "refresh_jobs" edges to the RefreshBatchJob entity.
func (_u *RepositoryUpdateOne) ClearRefreshJobs() *RepositoryUpdateOne {
	_u.mutation.ClearRefreshJobs()
	return _u
}

// RemoveRefreshJobIDs removes the "refresh_jobs" edge to RefreshBatchJob entities by IDs.
func (_u *RepositoryUpdateOne) RemoveRefreshJobIDs(ids ...uuid.UUID) *RepositoryUpdateOne {
	_u.mutation.RemoveRefreshJobIDs(ids...)
	return _u
}

// RemoveRefreshJobs removes "refresh_jobs" edges to RefreshBatchJob entities.
func (_u *RepositoryUpdateOne) RemoveRefreshJobs(v ...*RefreshBatchJob) *RepositoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRefreshJobIDs(ids...)
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdateOne) Where(ps ...predicate.Repository) *RepositoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepositoryUpdateOne) Select(field string, fields ...string) *RepositoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Repository entity.
func (_u *RepositoryUpdateOne) Save(ctx context.Context) (*Repository, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdateOne) SaveX(ctx context.Context) *Repository {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepositoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepositoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repository.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepositoryUpdateOne) check() error {
	if v, ok := _u.mutation.Owner(); ok {
		if err := repository.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "Repository.owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := repository.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Repository.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := repository.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Repository.full_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stars(); ok {
		if err := repository.StarsValidator(v); err != nil {
			return &ValidationError{Name: "stars", err: fmt.Errorf(`ent: validator failed for field "Repository.stars": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTMLURL(); ok {
		if err := repository.HTMLURLValidator(v); err != nil {
			return &ValidationError{Name: "html_url", err: fmt.Errorf(`ent: validator failed for field "Repository.html_url": %w`, err)}
		}
	}
	return nil
}

func (_u *RepositoryUpdateOne) sqlSave(ctx context.Context) (_node *Repository, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Repository.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repository.FieldID)
		for _, f := range fields {
			if !repository.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repository.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repository.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(repository.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(repository.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Stars(); ok {
		_spec.SetField(repository.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStars(); ok {
		_spec.AddField(repository.FieldStars, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(repository.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(repository.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(repository.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(repository.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.FetchedAt(); ok {
		_spec.SetField(repository.FieldFetchedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RefreshJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.RefreshJobsTable,
			Columns: []string{repository.RefreshJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRefreshJobsIDs(); len(nodes) > 0 && !_u.mutation.RefreshJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.RefreshJobsTable,
			Columns: []string{repository.RefreshJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefreshJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repository.RefreshJobsTable,
			Columns: []string{repository.RefreshJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(refreshbatchjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Repository{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
