// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/PavaoZornija1/github-tracker/ent/schema"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatch"
	"github.com/PavaoZornija1/github-tracker/internal/ent/refreshbatchjob"
	"github.com/PavaoZornija1/github-tracker/internal/ent/repository"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	refreshbatchFields := schema.RefreshBatch{}.Fields()
	_ = refreshbatchFields
	// refreshbatchDescCreatedAt is the schema descriptor for created_at field.
	refreshbatchDescCreatedAt := refreshbatchFields[1].Descriptor()
	// refreshbatch.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshbatch.DefaultCreatedAt = refreshbatchDescCreatedAt.Default.(func() time.Time)
	// refreshbatchDescUpdatedAt is the schema descriptor for updated_at field.
	refreshbatchDescUpdatedAt := refreshbatchFields[2].Descriptor()
	// refreshbatch.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refreshbatch.DefaultUpdatedAt = refreshbatchDescUpdatedAt.Default.(func() time.Time)
	// refreshbatch.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refreshbatch.UpdateDefaultUpdatedAt = refreshbatchDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refreshbatchDescID is the schema descriptor for id field.
	refreshbatchDescID := refreshbatchFields[0].Descriptor()
	// refreshbatch.DefaultID holds the default value on creation for the id field.
	refreshbatch.DefaultID = refreshbatchDescID.Default.(func() uuid.UUID)
	refreshbatchjobFields := schema.RefreshBatchJob{}.Fields()
	_ = refreshbatchjobFields
	// refreshbatchjobDescAttempt is the schema descriptor for attempt field.
	refreshbatchjobDescAttempt := refreshbatchjobFields[4].Descriptor()
	// refreshbatchjob.DefaultAttempt holds the default value on creation for the attempt field.
	refreshbatchjob.DefaultAttempt = refreshbatchjobDescAttempt.Default.(int)
	// refreshbatchjob.AttemptValidator is a validator for the "attempt" field. It is called by the builders before save.
	refreshbatchjob.AttemptValidator = refreshbatchjobDescAttempt.Validators[0].(func(int) error)
	// refreshbatchjobDescCreatedAt is the schema descriptor for created_at field.
	refreshbatchjobDescCreatedAt := refreshbatchjobFields[6].Descriptor()
	// refreshbatchjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshbatchjob.DefaultCreatedAt = refreshbatchjobDescCreatedAt.Default.(func() time.Time)
	// refreshbatchjobDescUpdatedAt is the schema descriptor for updated_at field.
	refreshbatchjobDescUpdatedAt := refreshbatchjobFields[7].Descriptor()
	// refreshbatchjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refreshbatchjob.DefaultUpdatedAt = refreshbatchjobDescUpdatedAt.Default.(func() time.Time)
	// refreshbatchjob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refreshbatchjob.UpdateDefaultUpdatedAt = refreshbatchjobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refreshbatchjobDescID is the schema descriptor for id field.
	refreshbatchjobDescID := refreshbatchjobFields[0].Descriptor()
	// refreshbatchjob.DefaultID holds the default value on creation for the id field.
	refreshbatchjob.DefaultID = refreshbatchjobDescID.Default.(func() uuid.UUID)
	repositoryFields := schema.Repository{}.Fields()
	_ = repositoryFields
	// repositoryDescOwner is the schema descriptor for owner field.
	repositoryDescOwner := repositoryFields[1].Descriptor()
	// repository.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	repository.OwnerValidator = repositoryDescOwner.Validators[0].(func(string) error)
	// repositoryDescName is the schema descriptor for name field.
	repositoryDescName := repositoryFields[2].Descriptor()
	// repository.NameValidator is a validator for the "name" field. It is called by the builders before save.
	repository.NameValidator = repositoryDescName.Validators[0].(func(string) error)
	// repositoryDescFullName is the schema descriptor for full_name field.
	repositoryDescFullName := repositoryFields[3].Descriptor()
	// repository.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	repository.FullNameValidator = repositoryDescFullName.Validators[0].(func(string) error)
	// repositoryDescStars is the schema descriptor for stars field.
	repositoryDescStars := repositoryFields[5].Descriptor()
	// repository.DefaultStars holds the default value on creation for the stars field.
	repository.DefaultStars = repositoryDescStars.Default.(int)
	// repository.StarsValidator is a validator for the "stars" field. It is called by the builders before save.
	repository.StarsValidator = repositoryDescStars.Validators[0].(func(int) error)
	// repositoryDescHTMLURL is the schema descriptor for html_url field.
	repositoryDescHTMLURL := repositoryFields[7].Descriptor()
	// repository.HTMLURLValidator is a validator for the "html_url" field. It is called by the builders before save.
	repository.HTMLURLValidator = repositoryDescHTMLURL.Validators[0].(func(string) error)
	// repositoryDescNotes is the schema descriptor for notes field.
	repositoryDescNotes := repositoryFields[8].Descriptor()
	// repository.DefaultNotes holds the default value on creation for the notes field.
	repository.DefaultNotes = repositoryDescNotes.Default.(string)
	// repositoryDescFetchedAt is the schema descriptor for fetched_at field.
	repositoryDescFetchedAt := repositoryFields[9].Descriptor()
	// repository.DefaultFetchedAt holds the default value on creation for the fetched_at field.
	repository.DefaultFetchedAt = repositoryDescFetchedAt.Default.(func() time.Time)
	// repositoryDescCreatedAt is the schema descriptor for created_at field.
	repositoryDescCreatedAt := repositoryFields[10].Descriptor()
	// repository.DefaultCreatedAt holds the default value on creation for the created_at field.
	repository.DefaultCreatedAt = repositoryDescCreatedAt.Default.(func() time.Time)
	// repositoryDescUpdatedAt is the schema descriptor for updated_at field.
	repositoryDescUpdatedAt := repositoryFields[11].Descriptor()
	// repository.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	repository.DefaultUpdatedAt = repositoryDescUpdatedAt.Default.(func() time.Time)
	// repository.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	repository.UpdateDefaultUpdatedAt = repositoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// repositoryDescID is the schema descriptor for id field.
	repositoryDescID := repositoryFields[0].Descriptor()
	// repository.DefaultID holds the default value on creation for the id field.
	repository.DefaultID = repositoryDescID.Default.(func() uuid.UUID)
}
