// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RefreshBatch is the predicate function for refreshbatch builders.
type RefreshBatch func(*sql.Selector)

// RefreshBatchJob is the predicate function for refreshbatchjob builders.
type RefreshBatchJob func(*sql.Selector)

// Repository is the predicate function for repository builders.
type Repository func(*sql.Selector)
